### ISSUE TITLE
Choose download folder

### ISSUE THREAD

**Issue by skarsgal** [henrypp/chrlauncher#1]
Hi Henry++,
At this moment the download folder is set up as '\bin' and it cannot to be changed.
Do You can create a setting page for choose download folder? 
For example '\Bin\Chrome' as in winPenPack or another download folder for adapt Your program to other Chromium Portable.

**Comment by henrypp** [comment]
Hi, yes of course it possible. Wait for next release.

**Comment by skarsgal** [comment]
Thanks,
this release 1.4 works very well.
