### ISSUE TITLE
Accept environment variables from command line

### ISSUE THREAD

**Issue by snakyjake1** [henrypp/chrlauncher#10]
Requesting a feature to expand environment variables when used int he command line or chrlauncher.ini file.

For example "%APPDATA%".

**Comment by henrypp** [comment]
you can use env. var. in INI, chrlauncher use ExpandEnvironmentStrings() func.

**Comment by snakyjake1** [comment]
When I used "--disk-cache-dir=%APPDATA%\Chromium_Cache", chrlauncher created the literal directory "%APPDATA", and did not expand the environment variable.

I also couldn't find "ExpandEnvironmentStrings" when searching the source code.

**Comment by henrypp** [comment]
I forgot, ExpandEnvironmentStrings() used in "_r_normalize_path()" function (https://github.com/henrypp/routine) for parameters in INI with relative directories.

And i can to add parsing env. strings in next release!
