### ISSUE TITLE
Ungoogled Chromium only checks GitHub releases for updates

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/chrlauncher#100]
The latest Windows binaries of Ungoogled Chromium available via its GitHub releases page is v55. This will be downloaded by chrLauncher. However, all newer binaries for Ungoogled Chromium are available via https://ungoogled-software.github.io/ungoogled-chromium-binaries/.

More specifically, you'll be redirected to https://github.com/squalus/ungoogled-chromium-binaries/releases/ for the Windows x64 binaries.

**Comment by woolyss** [comment]
Hello, I updated and tested the link. It works.
API: https://chromium.woolyss.com/api/v3/?os=windows&bit=64&type=ungoogled-chromium&out=json

**Comment by ltGuillaume** [comment]
Thanks, the new version is indeed now downloaded by chrLauncher. Next thing would be for chrLauncher to check in which folder of the extracted archive chrome.exe resides and move everything from there into /bin.

**Comment by panhans** [comment]
Yes, the binaries are placed in a sub folder named after the version. So we get with each version a new subfolder with another name.

**Comment by henrypp** [comment]
fixed
