### ISSUE TITLE
Updating fails due to connecting to known previously malicious IP

### ISSUE THREAD

**Issue by rugabunda** [henrypp/chrlauncher#101]
Its using a previously known malicious ip for updating, apparently and is blocked if you are using skynet or some similar app. https://otx.alienvault.com/indicator/ip/213.186.33.19

unbanning this ip allows it through but you may be placing yourself at risk.

**Comment by henrypp** [comment]
chrlauncher does not used hardcoded IP, used update urls from @woolyss website API
