### ISSUE TITLE
66.0.3359.139-1: Binaries for Windows - 64-bit is NOT ungoogled!

### ISSUE THREAD

**Issue by micha06de** [henrypp/chrlauncher#103]
The via crlauncher downloaded file is an official chromium build! It's goggled! What's going on?

**Comment by woolyss** [comment]
Hello,
Did you read the first page of the project?
https://github.com/henrypp/chrlauncher

In the **chrlauncher.ini**, change the download source if you want to install a different Chromium version.

**Comment by GeopJr** [comment]
As @woolyss suggested , change `ChromiumType=dev-codecs-sync` to `ChromiumType=ungoogled-chromium` in your chrlauncher.ini
