### ISSUE TITLE
Feature suggestion: Launch Chromium with extended arguments

### ISSUE THREAD

**Issue by minhducsun2002** [henrypp/chrlauncher#104]
I wish to have some arguments passed to `chrlauncher` so they'll be passed to Chromium. Sometimes switching back-and-forth between Chromium windows and terminal takes quite a time - I prefer doing everything in the terminal as long as I could - more productivity.

Thank you for `chrlauncher`, anyway!

**Comment by henrypp** [comment]
chrlauncher pass on all arguments to Chromium.

**Comment by henrypp** [comment]
Read more:
- [Pass on chrlauncher arguments into Chromium](https://github.com/henrypp/chrlauncher/issues/76#issuecomment-312444105)
