### ISSUE TITLE
Add option to download official channels 

### ISSUE THREAD

**Issue by joeparkerz** [henrypp/chrlauncher#106]
Add option to download official channels of Chrome as well.
Should be very easy to add.

https://github.com/cnjackchen/my-chrome/blob/master/MyChrome.au3

https://api.shuax.com/tools/getchrome

**Comment by henrypp** [comment]
### chrlauncher.ini
```ini
# official development builds from snapshots repository 
ChromiumType=dev-official

```

**Comment by joeparkerz** [comment]
What about stable, dev, beta, canary builds? Link above supports all.

**Comment by henrypp** [comment]
Chromium has ONLY development builds,

**Comment by joeparkerz** [comment]
Chrome! Not Chromium! Read the link again.

**Comment by henrypp** [comment]
>  #### Supported browser:
> - Launcher - Chromium and their clones (like Google Chrome, Yandex Browser and other legitimate trojans!).
> - Updater - Chromium only.

I think it possible, but 95% is not in my compitence. Chrome has only installer packages - it's bad.

**Comment by joeparkerz** [comment]
Well. Yes its possible. It contains chrome.7z files :)

Try it.

**Comment by joeparkerz** [comment]
MyChrome tool is updater for Chrome & Chromium ;)

Not sure why chrlauncher cannot also.
