### ISSUE TITLE
[solved] chrlauncher does not download ''official'' Chromium releases

### ISSUE THREAD

**Issue by woolyss** [henrypp/chrlauncher#107]
chrlauncher 2.4.3 does not download ''official'' Chromium 71+ releases for few days.

- Default settings
- `ChromiumType=dev-official` is the chosen parameter in the **chrlauncher.ini** file

I also talk about changes on Google servers at https://chromium.woolyss.com/?all=1#comment-3807
(This link will load many comments. It can be slow to display)

Tested on 64-bit Windows 10 with 64-bit and 32-bit chrlauncher.

Tested in chrlauncher 2.4.3, 2.4.1, 2.4 and 2.3 --> same result! :/

**Comment by woolyss** [comment]
Finally, I found the issue! ;)
Google renamed its ZIP files about Windows version of Chromium.
Now, all works nicely! ^^

**Comment by Hentioe** [comment]
Is it useful to move all the files in the subdirectory to the directory "bin"?

**Comment by woolyss** [comment]
Yes and no @Hentioe! ;)

For 64-bit Chromium, the simplest way is only to change a parameter in the **chrlauncher.ini** file
`ChromiumBinary=chrome.exe` to `ChromiumBinary=chrome-win\chrome.exe`

or

Move all the files in the subdirectory to the directory "bin".

**Comment by henrypp** [comment]
fixed
