### ISSUE TITLE
Manual Proxy Configuration

### ISSUE THREAD

**Issue by skyr1der** [henrypp/chrlauncher#108]
My company don't permit to modify the proxy configuration. It would be great to have a param in .ini file to override windows configuration (with credentials).

**Comment by henrypp** [comment]
done!

**Comment by troudbal** [comment]
Great ! How do you pass the proxy credentials ? I tried `Proxy=user:password@proxy:port` but it doesn't work.

**Comment by neatgz** [comment]
It does not work. I have an proxy on 127.0.0.1:8685, works well for other programs.
But It does not work on chrlauncher v2.5 , I tried both http and socks5 proxy.
