### ISSUE TITLE
Windows 10 - 1809: impossible to set chrlauncher as default browser (only chromium which opens a new profile window)

### ISSUE THREAD

**Issue by Tom4tot** [henrypp/chrlauncher#111]
Since a few updates, on Windows 10, it's impossible for me to pick chrlauncher (which launches my right chromium profile) as my default browser.

Right now, when I go to Windows settings, I can only pick "Chromium" which opens a new chrome profile (so I don't have access to all my settings / data as well as it doesn't open my taskbar shortcut but a new instance of Chrome).

See screenshot 1.
![screenshot_1](https://user-images.githubusercontent.com/32274750/48262213-d6bfca00-e475-11e8-8b55-262fbda0f136.png)

I can manually pick chrlauncher for file type but then when I open a link on another application it still opens links in a new chrome profile.

In "default apps by protocol", it's the same as on screenshot 1: for HTTP and HTTPS, I can't manually pick a program.

See screenshot 2.
![screenshot_2](https://user-images.githubusercontent.com/32274750/48262215-d7586080-e475-11e8-862e-1de82727e32e.png)

So basically, to sum up, Windows is really limitating users right now about default programs.

1) Am I doing something wrong?
2) Or is there a way to bypass it? Maybe changing the Chromium shortcut so it would open my profile. I already had more or less similar issues but you helped to fix them: https://github.com/henrypp/chrlauncher/issues/87

Thanks in advance for your help and for all your wonderful softwares in general. :)

PS: I've tried to report the issue in an older thread but it kept the thread as "closed", I don't think I can change the status that's why I'm making a new thread. I don't mean to "spam" or anything.

**Comment by earthsound** [comment]
I wonder if you hit a Windows 10 bug. [KB4467682](https://support.microsoft.com/en-us/help/4467682/windows-10-update-kb4467682) patched a bug similar to what you're experiencing. Are you still seeing this with a fully patched Windows 10?

**Comment by LsnmxNB** [comment]
@henrypp Hello, this BUG, can you fix it? Now WIN10 can not set chrlauncher as the default browser through SetDefaultBrowser.bat, thank you!

**Comment by LsnmxNB** [comment]
@Tom4tot  Hello, are you done?

**Comment by Tom4tot** [comment]
> 
> 
> @Tom4tot Hello, are you done?

I've switched to Firefox since then. But if you read my last message I gave a workaround. it probably still works.

**Comment by LsnmxNB** [comment]
@Tom4tot SetDefaultBrowser.bat How do you solve it?

**Comment by patrickHD** [comment]
I know this is old but for those still having this issue (or if the .bat isn't working for you), all you have to do is modify the registry key found at **Computer\HKEY_CLASSES_ROOT\ChromiumHTM.[long string]\shell\open\command** after setting chromium as your default browser (the long string might be different on your machine) The default value should be "....\chrlauncher\bin\chrome.exe" --single-argument %1

Add  your flags (found at ChromiumCommandLine in chrlauncher.ini) before '--single-argument'. For me the value ended up as **"C:\Programs\chrlauncher\bin\chrome.exe" --flag-switches-begin --user-data-dir=..\profile --no-default-browser-check --allow-outdated-plugins --disable-logging --disable-breakpad --flag-switches-end --single-argument %1**

After changing this links and files should open in chromium with your

**Comment by henrypp** [comment]
Tested on 1809, start SetDefaultBrowser from admin, and allociation is worked for me.

ps: updated 1809 to latest
ps2: chrlauncher directory contained not in %ProgramFiles%, maybe there is problem - not tested.
