### ISSUE TITLE
Is it possible to downgrade?

### ISSUE THREAD

**Issue by Tom4tot** [henrypp/chrlauncher#112]
Hi Henry++,

As I'm having more and more interest for privacy, I wanted to switch from dev-codecs-sync to ungoogled-chromium. The problem is that since Chromium version is older for the latter project, it seems that ChrLauncher considers there is no update to install, so it just ignores my request and launch my current chrome build.

Is that a normal behavior? It would make sense if it's for compatibility reasons. and then you can ignore this "issue".

IF the behavior is abnormal, maybe it's because I'm not setting up something properly? If it's "not my fault", then maybe I'd suggest that ChrLauncher, to know it it should install an update, should check both the build number and also check if the build type has changed. I don't know how hard it would be to implement. 

Thank you in advance.

**Comment by henrypp** [comment]
If you need downgrade you must delete Chromium binaries folder, no other way is possible!

**Comment by Tom4tot** [comment]
All right, thank you for your fast answer. At least it's clear!

It's not a big problem as all the stuff people want to keep is in the profile folder. So the solution is satisfying. Maybe add a line about it somewhere so people know? 👍

**Comment by Triramama** [comment]
> If you need downgrade you must delete Chromium binaries folder, no other way is possible!

Where's binaries folder?
