### ISSUE TITLE
lost all setting and extensions when copy Chromium to another pc

### ISSUE THREAD

**Issue by neatgz** [henrypp/chrlauncher#116]
chrlauncher v2.5.3
ChromiumType=stable-codecs-sync
I add some extensions and used normaly on my home PC (win10 1809 x64)
today , I copy the Chromium folder to U disk, and want to use it on my work PC(win10 1809 x64), but I lost all my settings and extensions when i open it on my work PC.
why are this happen?
thanks.

**Comment by woolyss** [comment]
Hello neatgz.

Bad news :/
But it is a normal feature of Chromium available for ALL chromium-based browsers. Nothing to do with chrlauncher.

Chromium has "Secure Preferences" feature based on the machine [SID](https://en.wikipedia.org/wiki/Security_Identifier). So extensions, certificates and passwords are not portable. The only way to migrate these data is to synchronize your data. 

Moreover, I know there is another possibility but it uses flags (which can be disappear at any time).
https://github.com/Eloston/ungoogled-chromium/pull/591

**Henry, you should put this info on your Github page and site!**

Links relative to this feature:
- https://github.com/portapps/brave-portable/issues/4 (About Brave)
- https://portableapps.com/apps/internet/google_chrome_portable (Read "App Notes" about Google Chrome)
- https://portableapps.com/apps/internet/opera_portable (Read "App Notes" about Opera)
- https://superuser.com/questions/634648/copy-chrome-extensions-from-one-computer-to-another
- https://productforums.google.com/forum/#!topic/chrome/oM4KdGkwSqE
- https://cs.chromium.org/chromium/src/chrome/browser/prefs/profile_pref_store_manager.cc (Chromium code source)

**Comment by neatgz** [comment]
Thank you for your reply.
Thanks a lot

**Comment by tomasz1986** [comment]
> Bad news :/
> But it is a normal feature of Chromium available for ALL chromium-based browsers (Google Chrome, Opera, Vivaldi, Brave...). Nothing to do with chrlauncher.

There is one exception which is the [Cent Browser](https://www.centbrowser.com). It is not tied to the hardware and keeps everything when copied to a different machine. The browser is unfortunately not open source, hence I do not use it personally.

The extensions folders with all the settings are actually kept intact even after moving everything to a different machine. Therefore, if you reinstall them, they will revert themselves to their previous state.

**Comment by tomasz1986** [comment]
Just for the record, Ungoogled Chromium is now fully portable with additional switches `--disable-machine-id` and `--disable-encryption`.

Source: https://github.com/Eloston/ungoogled-chromium/pull/591

**Comment by CrafterLaughter** [comment]
@woolyss @henrypp  Thanks for this info and all you guys do.

Bummer it is 2020 and Chromium devs have still kept the profiles dependent on sync (dependent on Google) in order to be transferable to another computer.  (Encryption is great but at least make it transferrable)

It is especially annoying that extensions have been deemed "encrypt by default," but not user's private bookmarks.

I was really hoping to switch from Firefox to Ungoogled Chromium for the security benefit of site isolation, but this is a deal breaker.  I guess I'll just have to stick it out with Firefox until their project Fission site isolation goes stable.

**Comment by graphixillusion** [comment]
@CrafterLaughter I'm totally agree with you. I'm searching from a long time for a solution to transfer extensions through machines but without any valid results. I've tried the method about restoring username's SID as suggested by the keepass guys but it doesn't work too.

**Comment by iGom** [comment]
Do we also lose history, settings, extension even when we update Chromium on the same machine??? Because that's what happened to me right now.
