### ISSUE TITLE
chrlauncher window closes too quickly

### ISSUE THREAD

**Issue by snakyjake1** [henrypp/chrlauncher#117]
The chrlauncher window closes too quickly, and I don't have a chance to see what it is telling me.

Is there an option for the window to wait until I press a button to continue?

**Comment by woolyss** [comment]
Hello snakyjake1, 

I tested today with **chrlauncher 2.5.3** on my Windows 10 Pro 1803.
All is ok.

For test, make sure you use a **STABLE** Chromium version.

If you test with a DEV version, it can be a revision issue. The DEV versions can be very unstable.
