### ISSUE TITLE
ungoogled version won't launched

### ISSUE THREAD

**Issue by 2anyone** [henrypp/chrlauncher#118]
use the last version `v.2.5.3`
modify ini to `ChromiumType=ungoogled-chromium`
all the other remain the default

run chrlauncher download version 67 of chromium
it made a bin in folder, seems all the chromium there

but when I tried to launched chrlauncher, it did nothing
checked the process explore (task manager)
chrome started up and quickly closed itself

please help. thanks.

**Comment by woolyss** [comment]
Hello @2anyone,
I tested today to install **ungoogled-chromium v2.5.3** on my Windows 10 Pro 1803 (64-bit).
chrlauncher works nicely. Chromium is launched. 

To help you:
* Which system (windows 7, 8, 10) do you use ? Tested on Windows 10. It is ok.
* Your system must be in 64-bit
* Maybe, your antivirus (Avast, AVG, Windows Defender...) remove it. 

![](https://i.imgur.com/CTfAvXR.png)

**Comment by 2anyone** [comment]
thanks, got this solved by refresh installed the ungoogle version of chromium 67, and replace the newer version's bin files from https://chromium.woolyss.com/, 

and don't forget edit ini to ungoogled-chromium
