### ISSUE TITLE
I would like to prevent crlauncher from starting Chrome.

### ISSUE THREAD

**Issue by VictorioBerra** [henrypp/chrlauncher#119]
I need to kick off crlauncher to auto-update my chrome binary but I do NOT want it to start Chrome. I thought the `/autodownload` flag would help but it did not.

This is for automated testing, so my Selenium tests can execute `.bin/chrome.exe` and monitor the process for exit.

## Use Case:
```powershell
Start-Process '.\chrlauncher 2.5 (64-bit).exe' -NoNewWindow -W
ait  -ArgumentList "/autodownload"
```

**Comment by StoyanDimitrov** [comment]
It would be handy for the translators of the application too.
