### ISSUE TITLE
Continuous repository no longer updated

### ISSUE THREAD

**Issue by jniggemann** [henrypp/chrlauncher#12]
The site http://chromium.woolyss.com/ reads:

###Important news

The Chromium team has removed few LKGR builders. (sources: 407399 and chromium-dev)
Consequently, the Continuous repository and official site (LKGR) are not updated since Friday, 18 Mar 2016 (1 month ago).

Does this affect chrlauncher?

**Comment by henrypp** [comment]
it affects only with "type=dev-official", beause official continuous build not updated since 18 March. use other type switch.
