### ISSUE TITLE
New provider for binaries of ungoogled-chromium

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/chrlauncher#120]
It seems that Marmaduke has recently taken up building win64 binaries for ungoogled-chromium. They're available from https://chromium.woolyss.com/?all=1#windows-64-bit-stable-ungoogled-marmaduke

Could you implement this in chrlauncher?

**Comment by woolyss** [comment]
Hello ltGuillaume,
I would like to add it too. Yes, it is possible but... https://github.com/henrypp/chrlauncher/issues/109#issuecomment-447126269

**Comment by ltGuillaume** [comment]
Aah I missed that new comment, thanks for explaining. Yeah, I hope Marmaduke will implement the conventions (and re-upload). Cheers!

**Comment by woolyss** [comment]
> Aah I missed that new comment

Normal, it is closed! ;)
I also hope.
