### ISSUE TITLE
The ungoogled-chomium version that is found using the api, is outdated

### ISSUE THREAD

**Issue by Gladuin** [henrypp/chrlauncher#121]
On https://chromium.woolyss.com/ the latest version is 71.0.3578.98, but when using the [api](https://chromium.woolyss.com/api/v3/?os=windows&bit=64&type=ungoogled-chromium&out=string), it only finds 67.0.3396.87

**Comment by woolyss** [comment]
Hello,
Henry updated chrlauncher yesterday and I updated the API today. All works nicely!
https://github.com/henrypp/chrlauncher/issues/109#issuecomment-447126269

Henry, you can close this thread! ;)
