### ISSUE TITLE
x64 build installing on every run

### ISSUE THREAD

**Issue by drujd** [henrypp/chrlauncher#123]
I have noticed that 2.5.4 x64 version keeps chrlauncherCache.bin in temp directory after download/extraction and extracts the binaries on every run. 32-bit build does not have the problem - once I switched to 32-bit version, chrlauncher extracted the data one last time and deleted the file. Switching to x64 again will then work - until new Chromium version is released.

**Comment by drujd** [comment]
This bug has been introduced with 2.5.4, previous versions work fine as they download to ZIP file instead. Maybe the problem is

**Comment by drujd** [comment]
I also believe that chrlauncher should not try to install cache files that remained from previous runs and should delete the cache file before performing any update check. Even though it might save time/bandwidth by avoiding redownloading again after an error, given that the name is constant, this might introduce some serious problems with multiple instances of Chromium, possibly installing different version / type if the file was created with a different instance/configuration.

**Comment by woolyss** [comment]
Hello everybody,

I have not got this issue. Please, check my video (stored on my server) :
https://chromium.woolyss.com/f/video-74.0.3684.0-r626039-nosync-win64-marmaduke.mp4

Environment :
- All is in 64-bit and up-to-date
- Proc: AMD Ryzen 7 1700x
- Windows 10 1809 (+ also tested in a Windows 7 inside a Virtualbox's VM)
- chrlauncher 2.5.4
- Chromium: https://github.com/macchrome/chromium/releases/tag/v74.0.3684.0-r626039-Win64

Please, can you share your environment or more info (screenshot, video) about your issue?

**Comment by nAFutro** [comment]
I've had the same issue on a fresh Windows 10 x64 installation. I noticed that the chrlauncher.exe was doing a lot of reading on C:\Users\LaptopMcLapFace\AppData\Local\Temp\chrlauncherCache.bin with every launch. After deleting that file in the directory, aka the %temp% folder, chrlauncher is running as usual. (perhaps deleting only that file is not enough, I deleted every file and folder in %temp% the first time so I'm not exactly sure)

**Comment by xtcrefugee** [comment]
I presume this is related to the issue I'm seeing where chrlauncher 2.5.4 is starting every time I run it and remaining in the system tray, even after I exit Chromium, with current/new versions of Chromium showing as unknown unless I set ChromiumLastCheck to 0. I have chrlauncher set to check for updates but not download automatically. Reverting to 2.5.3 fixes the issue, chrlauncher exits as expected.

**Comment by drujd** [comment]
I can replicate this issue on 2 different computers, both Windows 10 x64 1809. Every time a new update is released, until I manually delete chrlauncherCache.bin from the temp dir.

Log attached.
[chrome_installer.log](https://github.com/henrypp/chrlauncher/files/2824326/chrome_installer.log)
