### ISSUE TITLE
Local .htm files do not open

### ISSUE THREAD

**Issue by YellowSM** [henrypp/chrlauncher#125]
I run the launcher with the file name as an argument: `chrlauncher.exe d:\temp\1.htm`
But it is not transmitted to the Chromium. An empty tab opens.
But if I run as: `chrlauncher.exe file://d:\temp\1.htm` it works.
What's wrong?

I'm using version 2.5.4 of launcher (x64)

**Comment by Peter-Pwn** [comment]
Looks like all "random" arguments send to the launcher are ignored.

To solve the problem with double clicking a html file you can change the registry key HKEY_CLASSES_ROOT\chrlauncherHTML\shell\open\command "C:\YOUR_DIR\chrlauncher.exe" "%1" to "C:\YOUR_DIR\chrlauncher.exe" file://"%1"

**Comment by YellowSM** [comment]
Yeah, that's exactly what I did.
But I think that the launcher should work transparently and pass all the parameters to the browser, cutting only its own parameters.

**Comment by jboxberger** [comment]
Hello, 
i think there is the same problem is with the .url files - is there already a fix for the .htm/.html files?
By opening i get the error.

![image](https://user-images.githubusercontent.com/1545845/71566836-24a0f280-2abb-11ea-919a-d715bf2f62fd.png)

Content of a .url File
`
[InternetShortcut]
URL=https://github.com/henrypp/chrlauncher/issues/125
`
Example .url File
[url-example.zip](https://github.com/henrypp/chrlauncher/files/4008883/url-example.zip)

Kind Regards
