### ISSUE TITLE
Update installation on %LocalAppData%

### ISSUE THREAD

**Issue by convalise** [henrypp/chrlauncher#128]
On Chromium releases page (https://github.com/henrypp/chromium/releases), we choose to download between **chromium-sync.exe** and **chromium-sync.zip** (let's call them **exe** and **zip** respectively).

On **chrlauncher.ini** file we can set the **ChromiumDirectory** folder, and from where I understand, the chrlauncher updates Chromium by downloading the **zip** and overriding the contents of **ChromiumDirectory** folder.

I personally like to download the **exe** one, and I noticed the final "%LocalAppData%\Chromium\Application" folder has a different structure than the "portable" **zip** one.

So, my questions are:
- Since the folder structures are different, if I simply set the **ChromiumDirectory** to "%LocalAppData%\Chromium\Application" will it leave a "trash" old installation behind?
- Is there a different **ChromiumUpdateUrl** where chrlauncher downloads the **exe** instead of the **zip**? 
- By using the **exe** release should I not use chrlauncher update system?

PS: For **ChromiumType** I'm using **stable-codecs-sync**.

**Comment by woolyss** [comment]
@convalise: 
> (let's call them **exe** and **zip** respectively).

Ok I continue with that! ;)

Right. chrlauncher uses the ZIP file (or 7-zip file ; It depends of the release type). 
chrlauncher is not able to use the EXE file. Note few versions of Chromium ("ungoogled-version" for example) have no EXE file.

With chrlauncher, you can use different Chromium versions side by side in same time. Each chrlauncher can use its own **ChromiumDirectory** and **ChromiumCommandLine=--user-data-dir** 
As you know, you can easily change settings in the **chrlauncher.ini** file.

If you use the EXE version of Chromium, the goal is different. You do not need chrlauncher and you will update Chromium manually or with an other tool (bash script, chocolatey...).
(Just for info, the EXE file is a compressed 7-zip file. You can unzip it yourself if needed...and put its content in the chrlauncher **ChromiumDirectory** folder for example! ^^)

**Comment by convalise** [comment]
Hmm I see.

> Personally, I recommend chrlauncher for its simplicity and powerful settings.

I agree, I like it very much. :)
I guess it's best then if I delete the previous **exe** instalation and point the **ChromiumDirectory** to "%LocalAppData%\Chromium\Application" so chrlauncher can manage everything.

Thank you for your time!
Keep up the good work. :)
