### ISSUE TITLE
Ability to remove all chrlauncher registry keys?

### ISSUE THREAD

**Issue by brianj64** [henrypp/chrlauncher#13]
The current one doesn't seem to be working, it's still in the Default Programs list, and is still seen as a browser by Windows.

**Comment by henrypp** [comment]
import to registry "RegistryCleaner.reg" file.

**Comment by brianj64** [comment]
Does not work, still has the browser in "Default Programs" list even after running the reg file.

**Comment by henrypp** [comment]
it's not chrlauncher, this is Chromium. you can remove it from registry:
"HKEY_LOCAL_MACHINE\Software\RegisteredApplications" key with "Chromium" contain-word
