### ISSUE TITLE
issuse #123 persisting

### ISSUE THREAD

**Issue by ritmation** [henrypp/chrlauncher#131]
It seems that issue #123 hasn't been fixed. File chrlauncherCache.bin is still left by chrlauncher in %TEMP% directory after successful update.
I have various versions of chromium portable installed on my computer and upon starting a different version than the last updated, chrlauncher prompts me asking me to install an update which is left by previous update process.
chrlauncher version 2.5.5 x64

**Comment by drujd** [comment]
Yep, same problem here, I have not tested the fix properly. The situation is now improved in that at least after the second run the file IS deleted: in chrlauncher v2.5.4 extracts the update on every run, never deleting the file.

Still, the 32-bit version works flawlessly, even with x64 chromium builds, so...

**Comment by henrypp** [comment]
Check 2.5.6. I possible found where is bug!

**Comment by ritmation** [comment]
Works fine now. Thanks.
Работает отлично. Спасибо.
