### ISSUE TITLE
chrlauncher isn't opening up the profile that I have specified in the chrlauncher.ini file.

### ISSUE THREAD

**Issue by snakyjake1** [henrypp/chrlauncher#132]
I'm trying to open a URL from Windows using Chromium as the default browser via chrlauncher.
But chrlauncher isn't opening up the profile that I have specified in the chrlauncher.ini file.

In the Windows registry I have for the default open command: 
Chromium\CrLauncher\chrlauncher.exe" %1

Is there something special in the chrlauncher.ini file that I need to use to pass the command line parameter to the "ChromiumCommandLine" setting?

Or the "ChromiumBinary" setting?

Thanks,
Jake

**Comment by henrypp** [comment]
You set chrlauncher as default in Control Panel?

**Comment by henrypp** [comment]
Only this option set profile directory:
```ini
ChromiumCommandLine=--user-data-dir=..\profile --no-default-browser-check --allow-outdated-plugins --disable-logging --disable-breakpad
```
