### ISSUE TITLE
error while checking update

### ISSUE THREAD

**Issue by szylmzs** [henrypp/chrlauncher#134]
chrlauncher show a new version, when click download update, it shows "error while checking update"

**Comment by woolyss** [comment]
@szylmzs: Hello. It can be a temporary issue of your own network, my server, or an obsolete Chromium release. Please check at https://github.com/henrypp/chrlauncher/issues/142#issuecomment-518336260 and change the `ChromiumType=******` parameter in your **chrlauncher.ini** file

**Comment by silenceleaf** [comment]
same here today

**Comment by henrypp** [comment]
#142 duplicate
