### ISSUE TITLE
Installing wrong version

### ISSUE THREAD

**Issue by narcolepticinsomniac** [henrypp/chrlauncher#136]
I haven't used chrlauncher in a minute, but I wanted to test something in a dev branch without having to install Canary. Grabbed chrlauncher, checked the .ini beforehand, and it's set to `ChromiumType=dev-codecs-sync`, like I remember. I launch it, and it installs `74.0.3689.0` which I guess might've been a stable at some point, but is significantly behind the current stable. Most importantly, it's not dev. Not sure why I'm getting some random outdated stable version when dev is specified, but maybe something's changed since I last used it. Any advice would be appreciated.

Win 8.1.

**Comment by RyuConnor** [comment]
I'm also having this issue. chrlauncher.exe always downloads 74.0.3689.0. Best I can tell all settings are at default, so I'm not sure what I could have done to break the program.

**Comment by RyuConnor** [comment]
Poking at this a bit more, it appears the dev-codecs-sync has become unsupported. That's a bit of a hitch given that it is the default repository for chrlauncher. Moving to stable-codecs-sync results in a more modern release being fetched.

**Comment by henrypp** [comment]
`ChromiumType=dev-codecs-sync` is not official latest build, use `dev-official` instead
all versions you can see here https://chromium.woolyss.com/

**Comment by narcolepticinsomniac** [comment]
>`ChromiumType=dev-codecs-sync` is not official latest build, use `dev-official` instead

Okay, but the real issue here is that chrlauncher [still defaults to](https://github.com/henrypp/chrlauncher/blob/master/bin/chrlauncher.ini#L67) `dev-codecs-sync`, so if that build isn't getting the relevant updates anymore, I'm not sure why you wouldn't change it to one that is. I've always thought it should probably default to `stable-codecs-sync`, but the default should at least be one which receives regular updates and contains codecs. Seems like the readme could use an update as well.
