### ISSUE TITLE
"W32.Trojan.Dropper" detected in /32 directory

### ISSUE THREAD

**Issue by lirmwing** [henrypp/chrlauncher#137]
Upon portably installing chrlauncher, my antivirus was triggered for "W32.Trojan.Dropper" for the .exe within the /32/ directory. The other one though in /64/ was fine according to my antivirus upon scanning. Any explaination for what could've caused this?

**Comment by Technetium1** [comment]
@lirmwing this should be a pretty obvious as a false positive. If desired you can get more insight into the AV engine(s) at fault here by uploading whatever exe was marked bad to [VirusTotal](https://www.virustotal.com/gui/home/upload), [Jotti's Malware Scanner](https://virusscan.jotti.org/), and/or [MetaDefender](https://metadefender.opswat.com). If you do find out more, please update.

**Comment by henrypp** [comment]
false-positive, again #88
