### ISSUE TITLE
Problems with Windows 10 hibernate?

### ISSUE THREAD

**Issue by DonBongJohn** [henrypp/chrlauncher#138]
Every time I start my PC, which is using hibernate mode, I get this error message and Chromium launches. Autostart is clear. This ain't malware since it also happens on a fresh OS. Chromium or chrlauncher is set to be the default launcher by the provided batch file.

![image](https://user-images.githubusercontent.com/20537257/59872595-69283480-939a-11e9-9ebd-da0f8c35dbe7.png)

Is there a problem to fix this?
I don't know if I'm running a default config so you can have a look here.
https://pastebin.com/u836DN2J

Note: My only demandings are to have Chromium updated and the profile should be stored in Chromium\bin\profile\.

Thx 4 your help.

**Comment by henrypp** [comment]
Chromium launches, so it's Chromium problem.
Chromium cannot create folder, so check access rights for your conguration
