### ISSUE TITLE
Is it possible to download an exact version of Chrome?

### ISSUE THREAD

**Issue by VictorioBerra** [henrypp/chrlauncher#144]

**Comment by henrypp** [comment]
Chrome already have his own updater, chrlauncher supports only Chromium and build descibed [here](https://github.com/henrypp/chrlauncher/issues/142#issuecomment-518336260).

**Comment by VictorioBerra** [comment]
> Chrome already have his own update

Well, for automation purposes I have to update and launch chrome every time my code runs. Is there a way to force it to upload every time it starts?

**Comment by henrypp** [comment]
chrome does not have, only standart ways:

- https://www.youtube.com/watch?v=dP8hqvXvEX4
- or start chrome every time like that `chrome.exe about:about`
