### ISSUE TITLE
Quick question regarding passing command line string to SetDefaultBrowser?

### ISSUE THREAD

**Issue by rjbprime** [henrypp/chrlauncher#145]
Hello @henrypp,

I have a question regarding being able to pass chromium command line options to the SetDefaultBrowser.bat file. Is it possible to do this? As I am trying to set it to use

--high-dpi-support=1 --force-device-scale-factor=0.7

so that when I open links from my email client or such, when I haven't opened ChrLauncher yet, it opens in my desired size.

Please advise.

**Comment by henrypp** [comment]
`chrlauncher.ini` has `ChromiumCommandLine` parameter, you can change it's like this:

`ChromiumCommandLine=--user-data-dir=..\profile --no-default-browser-check --allow-outdated-plugins --disable-logging --disable-breakpad`
`ChromiumCommandLine=--user-data-dir=..\profile --no-default-browser-check --allow-outdated-plugins --disable-logging --disable-breakpad --high-dpi-support=1 --force-device-scale-factor=0.7`

**Comment by rjbprime** [comment]
I have worked out how to load the ```chrlauncher.ini``` via regedit, which was what I was having trouble doing.

By going into regedit, and changing ```"X:\path\to\chrlauncher.exe" "%1"``` under both ```HKCR>chrlauncherHTML>shell>open>command>``` and ```HKCR>chrlauncherURL>shell>open>command>``` to ```"X:\path\to\chrlauncher.exe" "/ini .\chrlauncher.ini" "%1"```, I managed to have chrlauncher load the ini file when opening it from my email and chat clients, **without** chrlauncher or chromium having being open.

Then, by exporting the keys, I copied the regedit formatted ```"/ini .\chrlauncher.ini"``` section to the SetDefaultBrowser.bat file, under the ```set "CHRLAUNCHER_ARGS=\"%CHRLAUNCHER_PATH%\"  \"%%1\""``` section, so it now reads ```set "CHRLAUNCHER_ARGS=\"%CHRLAUNCHER_PATH%\" \"/ini .\\chrlauncher.ini\" \"%%1\""```, used the ```RegistryCleaner.reg``` file to clean out the keys, before running ```SetDefaultBrowser.bat``` as admin.

Upon testing it, it works how I wish it to. If you choose to change the CHRLAUNCHER_ARGS section in the next version, would you take the changes from here, or would you prefer a pull request?

**Comment by henrypp** [comment]
`chrlauncher.ini` by default loading from `chrlauncher` directory, why you need this mindfuck?

**Comment by rjbprime** [comment]
Because when I load Thunderbird, or Discord, or anything else that calls chrLauncher, without it being opened at all, such as when I first turn my laptop on, I check my emails, open discord, then open chrLauncher, 95% of the time in that order, if I click on a link in any of the first two, it opens a chrLauncher then Chromium window, that ***does not*** respect the ```--high-dpi-support=1 --force-device-scale-factor=0.7``` cmdline options. Setting those options in regedit via the BAT file, or doing it manually, respects my decision to run Chromium in a reduced dpi.

I understand if this is something you do not wish to discuss, I was only making a suggestion. I'll be closing this then.
