### ISSUE TITLE
Pasting Images From Paint Causes Them to be Blank

### ISSUE THREAD

**Issue by FluorescentGreen5** [henrypp/chrlauncher#147]
I can paste in images that were copied from another webpage, but when I select part of an image in Paint and paste it into another website, the image is either blank white or fully transparent.

**Comment by henrypp** [comment]
How this is are related with chrlauncher?

**Comment by FluorescentGreen5** [comment]
Sorry, I'll repost this in the Ungoogled Chromium issues section instead.
