### ISSUE TITLE
Upgrade broke my Profile

### ISSUE THREAD

**Issue by snakyjake1** [henrypp/chrlauncher#148]
I upgraded to Chromium Version 77.0.3865.75 (Official Build) (64-bit), and now my Profile won't work.

I can browse with a new profile, guest, or incognito.

I also tried launching with all plugins disabled, and cleared my history.

What else might I try?

**Comment by henrypp** [comment]
chrlauncher is not change Chromium profile at any time. Here is answer https://github.com/henrypp/chrlauncher/issues/116#issuecomment-444426692.
