### ISSUE TITLE
Update Adobe Flash Player?

### ISSUE THREAD

**Issue by snakyjake1** [henrypp/chrlauncher#15]
Updated from v50 to v51 today, and I'm getting a message about Adobe Flash Player not being up to date.  Not sure if the two events are related.  But definitely not sure how to update Adobe Flash.

**Comment by henrypp** [comment]
are you used argument parameter `--allow-outdated-plugins` in `ChromiumCommandLine` key?

here PPAPI updates in ZIP:
http://effect8.ru/soft/media/adobe-flash-player-portable.html
