### ISSUE TITLE
Need help building

### ISSUE THREAD

**Issue by vincenthawke** [henrypp/chrlauncher#151]
I cloned the main repo in VS2019 via Team Explorer. Then I downloaded the routines repository and added that. I set the additional include directories to `src\include` and additional library direcotries to `src\lib\64`. I also set under Input-> Additional dependencies `ntdll.lib` but I still can't build?

Error list: ```1>------ Build started: Project: chrlauncher, Configuration: Debug x64 ------
1>rapp.cpp
1>routine.cpp
1>rstring.cpp
1>unzip.cpp
1>main.cpp
1>C:\Users\Home1\source\repos\routine\rapp.cpp(599): warning : resource id is not defined IDS_QUESTION_FLAG_CHK
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(104,7): error C3861: '_r_str_isempty': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(109,5): error C3861: '_r_str_copy': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(115,7): error C3861: '_r_str_isempty': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(115,34): error C3861: '_r_str_compare': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(156,2): error C3861: '_r_ctrl_settabletext': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(157,125): error C3861: '_r_str_isempty': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(157,2): error C3861: '_r_ctrl_settabletext': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(158,104): error C3861: '_r_str_isempty': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(158,2): error C3861: '_r_ctrl_settabletext': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(159,2): error C3861: '_r_ctrl_settabletext': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(186,2): error C3861: '_r_str_copy': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(187,2): error C3861: '_r_str_printf': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(193,4): error C3861: '_r_str_printf': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(200,4): error C3861: '_r_str_printf': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(203,119): error C2146: syntax error: missing ')' before identifier 'PR_SIZE_T'
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(203,2): error C3861: '_r_str_copy': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(203,119): error C2146: syntax error: missing ';' before identifier 'PR_SIZE_T'
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(203,119): error C2065: 'PR_SIZE_T': undeclared identifier
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(203,129): error C2143: syntax error: missing ';' before 'string'
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(203,168): error C2059: syntax error: ')'
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(203,169): error C2059: syntax error: ')'
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(203,183): error C2059: syntax error: ')'
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(239,2): error C3861: '_r_str_copy': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(240,2): error C3861: '_r_str_printf': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(242,2): error C3861: '_r_str_copy': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(244,2): error C3861: '_r_str_copy': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(260,10): error C3861: '_r_str_compare': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(260,53): error C3861: '_r_str_compare': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(264,15): error C3861: '_r_str_compare': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(264,58): error C3861: '_r_str_compare': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(268,15): error C3861: '_r_str_compare': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(268,58): error C3861: '_r_str_compare': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(272,15): error C3861: '_r_str_compare': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(272,58): error C3861: '_r_str_compare': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(276,15): error C3861: '_r_str_compare': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(276,58): error C3861: '_r_str_compare': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(284,7): error C3861: '_r_str_compare': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(285,7): error C3861: '_r_str_compare': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(286,7): error C3861: '_r_str_compare': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(287,7): error C3861: '_r_str_compare': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(294,6): error C3861: '_r_str_cat': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(295,6): error C3861: '_r_str_cat': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(300,6): error C3861: '_r_str_cat': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(301,6): error C3861: '_r_str_cat': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(302,6): error C3861: '_r_str_cat': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(342,4): error C3861: '_r_str_cat': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(343,4): error C3861: '_r_str_cat': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(344,4): error C3861: '_r_str_cat': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(345,4): error C3861: '_r_str_cat': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(346,4): error C3861: '_r_str_cat': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(358,41): error C3861: '_r_str_isempty': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(358,3): error C3861: '_r_tray_setinfo': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(366,41): error C3861: '_r_str_isempty': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(366,3): error C3861: '_r_tray_setinfo': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(371,41): error C3861: '_r_str_isempty': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(371,3): error C3861: '_r_tray_setinfo': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(389,8): error C3861: '_r_str_compare': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(418,20): error C3861: '_r_str_isempty': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(427,3): error C3861: '_r_str_copy': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(429,7): error C3861: '_r_str_isempty': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(431,3): error C3861: '_r_str_cat': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(445,7): error C3861: '_r_str_isempty': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(445,46): error C3861: '_r_str_isempty': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(483,2): error C2065: 'rstringmap1': undeclared identifier
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(483,14): error C2146: syntax error: missing ';' before identifier 'result'
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(483,14): error C2065: 'result': undeclared identifier
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(504,50): error C2039: 'GetProxyConfiguration': is not a member of 'rapp'
1>C:\Users\Home1\source\repos\routine\rapp.hpp(133): message : see declaration of 'rapp'
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(509,8): error C3861: '_r_inet_downloadurl': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(513,48): error C2065: 'result': undeclared identifier
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(529,7): error C2065: 'result': undeclared identifier
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(531,65): error C2065: 'result': undeclared identifier
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(531,3): error C3861: '_r_str_copy': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(532,63): error C2065: 'result': undeclared identifier
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(532,3): error C3861: '_r_str_copy': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(534,20): error C2065: 'result': undeclared identifier
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(573,2): error C3861: '_r_str_printf': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(585,49): error C2039: 'GetProxyConfiguration': is not a member of 'rapp'
1>C:\Users\Home1\source\repos\routine\rapp.hpp(133): message : see declaration of 'rapp'
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(590,7): error C3861: '_r_inet_downloadurl': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(710,6): error C3861: '_r_str_replace': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(713,22): error C3861: '_r_path_getfilename': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(715,10): error C3861: '_r_str_isempty': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(715,36): error C3861: '_r_str_isempty': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(720,10): error C3861: '_r_str_compare': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(727,7): error C3861: '_r_str_trim': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(754,6): error C3861: '_r_str_replace': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(756,24): error C3861: '_r_path_getdirectory': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(759,82): error C3861: '_r_str_compare': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(778,28): error C3861: '_r_path_getdirectory': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(885,37): error C3861: '_r_str_isempty': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(888,5): error C3861: '_r_str_replace': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(890,21): error C3861: '_r_path_getfilename': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(897,9): error C3861: '_r_str_compare': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(904,6): error C3861: '_r_str_trim': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(920,4): error C3861: '_r_str_replace': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(922,22): error C3861: '_r_path_getdirectory': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(925,75): error C3861: '_r_str_compare': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(939,20): error C3861: '_r_path_getdirectory': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(997,20): error C3861: '_r_path_getfilename': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(1014,3): error C3861: '_r_str_copy': identifier not found
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(1022,38): error C2660: '_r_fs_rmdir': function does not take 2 arguments
1>C:\Users\Home1\source\repos\routine\routine.hpp(249,6): message : see declaration of '_r_fs_rmdir'
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(1059,3): error C3861: '_r_tray_toggle': identifier not found
1>Generating Code...
1>C:\Users\Home1\source\repos\chrlauncher\src\main.cpp(1059,34): fatal error C1003: error count exceeds 100; stopping compilation
1>Done building project "chrlauncher.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========```

**Comment by henrypp** [comment]
#150
