### ISSUE TITLE
Couldn't load PDF plugin on developer Chrome version

### ISSUE THREAD

**Issue by Suncatcher** [henrypp/chrlauncher#152]
Doesn't load PDF files inline on Version 79.0.3917.0 (Official Build) (64-bit).

![Annotation 2019-10-06 230730](https://user-images.githubusercontent.com/6388034/66284689-9f78b980-e88e-11e9-8d93-385ec3ca4e23.jpg)

Don't know if this is a launcher issue or Chromium issue, just in case I posted issue in [their bugtracker too](https://bugs.chromium.org/p/chromium/issues/detail?id=1010997&can=4&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified).

**Comment by henrypp** [comment]
yes,it's chromium problem.
