### ISSUE TITLE
auto update removes all extensions

### ISSUE THREAD

**Issue by mooglestiltzkin** [henrypp/chrlauncher#154]
I noticed that after the auto update, that all my chrome extensions added all got removed. how to stop that from happening when updating?

**Comment by mooglestiltzkin** [comment]
i used https://github.com/woolyss/chromium-web-store

to add chrome extensions to the browser. but now they are all gone.

**Comment by henrypp** [comment]
chrlauncher is not change Chromium profile at any time. Here is answer https://github.com/henrypp/chrlauncher/issues/116#issuecomment-444426692.
