### ISSUE TITLE
Downloads update but won't install

### ISSUE THREAD

**Issue by drrobertkelley** [henrypp/chrlauncher#156]
I got stuck on version 74.0.3689.0.  Every time chrlauncher downloads an update, it freezes and won't install it. I'm not very savvy here. Is there a way I can show an error log to troubleshoot this?

**Comment by mobinhaq** [comment]
I was experiencing this issue myself. It has to do with the .7z files support. **Just download the latest chrlauncher version 2.5.6. Close browser, replace the existing chrlauncher files on PC with the downloaded files**.  Updates should start working again as normal.

**Comment by drrobertkelley** [comment]
It worked! Thanks! Just for anyone else experiencing this issue:
1. Don't delete Chrome files, just the chrlauncher files in the 32 or 64 folder.
2. I had to end the chrlauncher task in the Task Manager to replace chrlauncher.exe.
