### ISSUE TITLE
add chromium-web-store

### ISSUE THREAD

**Issue by KonoromiHimaries** [henrypp/chrlauncher#158]
https://github.com/NeverDecaf/chromium-web-store#chromium-web-store

**Comment by woolyss** [comment]
@KonoromiHimaries: chromium-web-store is an extension for ungoogled-chromium because you cannot directly install extensions in ungoogled-chromium.

On other Chromium versions, you can install extensions directly from the Chrome Web Store.

**Comment by KonoromiHimaries** [comment]
https://github.com/henrypp/chrlauncher/issues/33
