### ISSUE TITLE
Error while checking update

### ISSUE THREAD

**Issue by Dovahkiin-Warrior** [henrypp/chrlauncher#159]
chrlauncher was working fine for me for the past couple days. Suddenly, it is no longer working. I tried checking chromium.woolyss.com and it doesn't work for me either. My desktop PC and laptop both have this issue, and I have also checked my DNS settings to be sure they're not wrong. No results. Any ideas? The error is checking for updates.

**Comment by henrypp** [comment]
What you do? What version? What OS. Any info?

**Comment by Dovahkiin-Warrior** [comment]
I have chrlauncher.exe in C:\Users\<myUserFolder>\Desktop\chrlauncher\64\chrlauncher.exe

It is pinned to task bar on both machines. Release is 2.5.6

OS is Windows 10 Pro 64-Bit, v1909, build 18362.476

Laptop specs is 
```
CPU: Intel Core i7 4720hq
RAM: 16GB Kingston DDR3 1600MHz
GPU: NVIDIA GeForce GTX 960M
```

Desktop specs is
```
CPU: 2x Intel Xeon L5640
RAM: 48GB Mushkin DDR3 1333MHz
GPU: PNY GeForce GTX 1060-3GB OC
```

I will try the latest version (2.5.7) now and will report back if it works.

**Comment by Dovahkiin-Warrior** [comment]
Okay, so latest version allows chrome to launch without the update working.

Oddly enough, my girlfriend is connected to the same network as me and has the same desktop specs, except hers has a 6GB GPU, and she can run chrlauncher and it will get updates no problem.

**Comment by Dovahkiin-Warrior** [comment]
Update: I had to whitelist your host on my hardware firewall. Not sure what caused it to become blocked in the first place... Resolved.
