### ISSUE TITLE
Launching from command line launches update.

### ISSUE THREAD

**Issue by snakyjake1** [henrypp/chrlauncher#16]
Launching from the command line with Chromium already running will still check for a new version and attempt to install the update.  But when the update realizes Chromium is running, it will error, and then Chromium will become unstable.  I'm guessing the instability is because some file are missing between the update.

Not sure if this is because of launching from the command line, or if the same could occur launching from the .EXE.

The command line (or exe) should check if an instance is already running.

**Comment by henrypp** [comment]
What problem? Because `chrlauncher` check for updates every time as start or cannot install update when `Chromium` is running? Before install update his check for running browser and wait until you close `Chromium` and press `Continue` button. What problem on you?

**Comment by snakyjake1** [comment]
I launch chrlauncher every time.  
Why?
Because I'm running Chromium in portable mode and I require using the command line parameters in the .ini file.

Here are the events:

I have an application that launches an external browser from the command line:
chrlauncher.exe

The chrlauncher update window appears.
chrlauncher downloads the update.
chrlauncher attempts to install update.
chrlauncher has a popup window "For install new version, need terminate all processes in browser folder."  Retry/Cancel.
I click cancel.
I now receive a message "Unable to start browser (0x000036b1)".

First problem:
With Chromium already running, why is chrlauncher launching the update?  Trying to install?  It can't install, so why bother checking for update, download, or attempt to install?  
Or maybe there needs to be an option to terminate all running instances of Chromium (which I don't like losing all my tabs).

Second problem:
I can no longer launch chrlauncher.exe from the command line.  I get the message "Unable to start browser (0x000036b1)".

Third problem:
Chromium is now broken.
I can't create new tabs.
I exit Chromium.
I can no longer launch chrlauncher.
It is all broken.
To fix it, I have change ChromiumCheckPeriodLast=0, and install the update.

**Comment by snakyjake1** [comment]
This issue shouldn't be closed.  The same problem happened today.
I launch Chrome via chrlauncher.  It tried to install the update when Chromium is running.  Then Chromium crashes.

**Comment by henrypp** [comment]
remove whole Chromium "bin" folder, "chrlauncher.exe" and "chrlauncher.ini" files and download latest version from releases section of this repository, and wait when chrlauncher finished downloading latest version of Chromium.

0x000036b1 - Error Lookup is says its problem with your Chromium distributive.

**Comment by snakyjake1** [comment]
will do.  thanks.
I think the "0x000036b1" message is because of a partial upgrade.

**Comment by henrypp** [comment]
is the same
