### ISSUE TITLE
Possible to force a new instance?

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/chrlauncher#160]
I often run a separate Chromium instance with --app="[some-url]" among other parameters. While such an instance is running, chrlauncher.exe won't start up its own instance anymore, figuring it's already running.

Is there a way for chrlauncher.exe to ignore these --app="" instances or force chrlauncher.exe to open a new instance?

**Comment by henrypp** [comment]
Yes, [https://peter.sh/experiments/chromium-command-line-switches/#new-window](-new-window)

**Comment by ltGuillaume** [comment]
Unfortunately, that won't work when added to `ChromiumCommandLine=` in `chrlauncher.ini`
