### ISSUE TITLE
don't work UserAgent in chrlauncher.ini

### ISSUE THREAD

**Issue by k-dmitrii** [henrypp/chrlauncher#161]
v.2.5.7, win8.1

# Set custom useragent (string):
#UserAgent=Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
UserAgent=Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 5 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko; googleweblight) Chrome/38.0.1025.166 Mobile Safari/535.19

but any site show: Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

**Comment by henrypp** [comment]
this option sets useragent for a chrlauncher, not <browser name>
