### ISSUE TITLE
cannot built because of missing files

### ISSUE THREAD

**Issue by ulu** [henrypp/chrlauncher#165]
I used latest snapshot (ZIP) of current sources (Latest commit ef36ca5 Dec 13, 2019) and got:
1>c1xx : fatal error C1083: Cannot open source file: '..\routine\rapp.cpp': No such file or directory
1>c1xx : fatal error C1083: Cannot open source file: '..\routine\routine.cpp': No such file or directory
1>c1xx : fatal error C1083: Cannot open source file: '..\routine\rstring.cpp': No such file or directory
1>c:\Code\chrlauncher-master\src\main.cpp(7,10): fatal error C1083: Cannot open include file: 'rapp.hpp': No such file or directory

**Comment by henrypp** [comment]
https://github.com/henrypp/chrlauncher/issues?utf8=✓&q=is%3Aissue+is%3Aclosed+routine

**Comment by ulu** [comment]
Maybe its more helpful to give the correct answer instead of a duplicates list. Others will also tend to open a new issue.

Currently the correct answer seems to be this one: https://github.com/henrypp/chrlauncher/issues/78#issuecomment-313871248
