### ISSUE TITLE
Unable to unzip chromium when the 7z file come from the standard build process

### ISSUE THREAD

**Issue by woolyss** [henrypp/chrlauncher#166]
Hello Henry,

I know that my title is not very clear! ;)

I prefer to show the comments on my site relative to this issue. (These links will show all comments).
https://chromium.woolyss.com/?all=1#comment-5180 
and https://chromium.woolyss.com/?all=1#comment-5370

Hibbiki, the developer of stable Chromium version on Windows says :
> As far as I can see, this is an issue with chrlauncher not accepting standard output from Chromium build target. All my files come directly from Chromium build process invoked via command like this `autoninja -C out/stable-sync-x64 mini_installer.exe`. I don't process the files in any shape or form. If being double-packed is an issue I can upload chrome.7z instead of chrome.packed.7z, however it's over 200MiB in size as it uses no compression. Would that be fine? I don't plan or want to offer any binaries that are product of some other tool or were post-processed by some other tool other than Chromium's own build system.

----

Henry, to help you, I prepared 2 chrlauncher archives to test! ^^

- https://chromium.woolyss.com/f/chrlauncher-win64-stable-codecs-sync.zip
This chrlauncher will download the chromium release of Hibbikki.
Here, Hibbikki has modified his Chromium build process to be compatible with chrlauncher.
**Result: It works but the standard build process of Chromium is not respected.** 
For info, API url: https://chromium.woolyss.com/api/v3/?os=windows&out=json&type=stable-codecs-sync

- https://chromium.woolyss.com/f/chrlauncher-win64-stable-codecs-sync-78.zip
This chrlauncher will download the chromium v78 release of Hibbikki.
Here, Hibbikki used the standard Chromium build process.
**Result: chrlauncher cannot unzip it because it does not know its file structure.**
For info, API url: https://chromium.woolyss.com/api/v3/?os=windows&out=json&type=stable-codecs-sync-78

So please, is it possible for you to improve chrlauncher about unzip process?
The best thing I see is when chrlauncher see a zip or 7z archive file, it automatically unzip it until there is no archive file inside. Limit the recursivity to 2 unzipped processes should be enough.

What do you think? Is it possible?

**Comment by henrypp** [comment]
> As far as I can see, this is an issue with chrlauncher not accepting standard output from Chromium build target. All my files come directly from Chromium build process invoked via command like this autoninja -C out/stable-sync-x64 mini_installer.exe. I don't process the files in any shape or form. If being double-packed is an issue I can upload chrome.7z instead of chrome.packed.7z, however it's over 200MiB in size as it uses no compression. Would that be fine? I don't plan or want to offer any binaries that are product of some other tool or were post-processed by some other tool other than Chromium's own build system.

Hello, i understand that and can help you if you can tell me why official builds ("dev-official" etc.) do not have this double-packing archive structure?

**Comment by woolyss** [comment]
Ok. Currently, all works.
So wait for the https://github.com/Hibbiki answer.
(Note this is the end of the year. We probably see that, next year!)

**Comment by TPS** [comment]
_@woolyss IfF you're trying to flag @Hibbiki for an answer, try this syntax._

**Comment by mikhaelkh** [comment]
@henrypp, it's not that poor and useless, official installers use double-packing structure `mini_installer.exe` -> `chrome.7z` -> `Chrome-bin` -> `chrome.exe`.

If inner `chrome.7z` packed in no compression mode, resulting archive will be only a few bytes larger, which you seem to have a serious problem with.

But the difference between zip and 7z is a lot more significant, and copying official procedure would result in a much larger output.

**Comment by Hibbiki** [comment]
> Hello, i understand that and can help you if you can tell me why official builds ("dev-official" etc.) do not have this double-packing archive structure (`chrome.packed.sync.7z` -> `chrome.7z` -> `Chrome-bin` -> `chrome.exe`)?

Who knows, try asking Chromium developers or building one yourself with `autoninja -C out/stable-sync-x64 mini_installer.exe` and see what results it produces if you doubt me.
