### ISSUE TITLE
chrlauncher ignores auto download setting

### ISSUE THREAD

**Issue by syndenbock** [henrypp/chrlauncher#171]
In my chrlauncher.ini, I have set `ChromiumAutoDownload=false`, but when chrlauncher finds an update, it automatically downloads it anyways.
This worked in earlier versions if I remember correctly.

**Comment by machin40** [comment]
Same here

**Comment by semecan** [comment]
I can now confirm that the setting worked in 2.5.6 .

**Comment by freezewind** [comment]
Same here

**Comment by AdKiller** [comment]
chrlauncher Version: 2.5.7

ChromiumAutoDownload=false

Doesn't work. update gets downloaded & installed automatically.

**Comment by bakugo** [comment]
Two year old bug ignored... something tells me this software isn't very well maintained.

**Comment by AdKiller** [comment]
@henrypp thanks for the update! but why is it downloading developer build by default?!
