### ISSUE TITLE
Does it have to use 64bit chrlauncher on 64bit Windows?

### ISSUE THREAD

**Issue by kajamin** [henrypp/chrlauncher#177]
Got the warning message which suggest me use 64bit chrlauncher instead. I skipped this warning and everything seems just fine. Test with 64bit chrlauncher, looks like it works identical as 32bit version. So what's the difference between 32bit and 64bit version? Does it matter if I use 32bit on a 64bit Windows? 

Thank you!

**Comment by TPS** [comment]
32-bit will _work_ fine, but 64-bit is _potentially_ faster & more secure.

**Comment by kajamin** [comment]
> 32-bit will _work_ fine, but 64-bit is _potentially_ faster & more secure.

Thanks for clarifying!
