### ISSUE TITLE
Auto-delete of old Chromium versions?

### ISSUE THREAD

**Issue by death-owl** [henrypp/chrlauncher#180]
Hello. I recently started using Chrlauncher and it seems like a very good program, so thanks for it.

There's just one issue I've noticed so far: When it updates Chromium, should it auto-delete the old version(s)? Or was there some option I missed?

So, after it updated my Chromium from 81.0.4044.92 to 81.0.4044.113, I had two Chromium folders in the bin folder: both 81.0.4044.92 and 81.0.4044.113, both around 180 megabytes, taking up twice the disk space they should. I deleted the older one manually.

I would prefer for it to clean up the old version when it installs the new one, or at least have an option in the ini file for it to do so.

Some of my settings in the ini file, in case this behavior depends on any of these:
ChromiumAutoDownload=false
ChromiumBringToFront=false
ChromiumWaitForDownloadEnd=false
ChromiumType=stable-codecs-sync
ChromiumCheckPeriod=2

**Comment by woolyss** [comment]
>  should it auto-delete the old version(s)?

No. As you know, you see the old Chromium versions in the "bin" folder.

If think @henrypp can easy  add an option to remove automatically old Chromium versions via a parameter (like `ChromiumRemoveOldVersions=true`) in the .ini file. This is his choice 😉

**Comment by semecan** [comment]
I don't think the behaviour comes from chrlauncher itself, as when using ungoogled-chromium, the structure in the "bin" folder is completely different.
I think the application simply downloads the archive from github and unpacks it in the "bin" folder, without emptying the folder beforehand. The "old versions" come from the structure of the release archives of [this](https://github.com/Hibbiki/chromium-win64) repo.
So an option to remove the old version beforehand would be great, but an option to keep specific versions is propably not as easily realizable.

**Comment by sirjeannot** [comment]
there must be some logic known to chrlaucher as it has knowledge as where the current bin is located to start it.

**Comment by semecan** [comment]
I'm pretty sure it just statifcally launches "./bin/chrome.exe".

**Comment by henrypp** [comment]
chrlauncher always cleanup .\bin folder before installation, you have use old version of chrlauncher.

**Comment by semecan** [comment]
I'm using version 2.5.7 which is the latest release listed on github.

**Comment by death-owl** [comment]
I've also been using 2.5.7.

**Comment by henrypp** [comment]
Yes, this is bug. I fix this soon.

**Comment by semecan** [comment]
Thank you very much for your great work!

**Comment by AdKiller** [comment]
I was about to post the same question. today I noticed 2 GB of old versions in ChromiumPortable\bin folder.
