### ISSUE TITLE
Chrlauncher update Chromium fine... but not the version number in Windows registry

### ISSUE THREAD

**Issue by ggbce** [henrypp/chrlauncher#182]
I use ChrLauncher 2.5.x (2.5.7 since december 2019) 

and it work very fine to update my Chromium to latest version. The tool update the browser himself without problem... But I finally observed in Windows informations that Chromium still telling the installed version was the original version installed. The version number is not updated.

When we use a scan software tool (GLPI, LanSweeper, SCCM, etc.) to take an heartbeat of your computers, this is not very interesting because it report the wrong version installed.

![true_version](https://user-images.githubusercontent.com/17770263/89913533-d6f87680-dbc1-11ea-9150-ebaef19a646c.PNG)
![wrong_version_add-remove_classic](https://user-images.githubusercontent.com/17770263/89913544-d9f36700-dbc1-11ea-8719-74a907258ca4.PNG)
![wrong_version_add-remove10](https://user-images.githubusercontent.com/17770263/89913558-dcee5780-dbc1-11ea-9543-161a4afb016e.PNG)
![wrong_version_registry](https://user-images.githubusercontent.com/17770263/89914203-abc25700-dbc2-11ea-9127-86cf0d632051.PNG)
![wrong_version_registry_uninstall](https://user-images.githubusercontent.com/17770263/89914215-aebd4780-dbc2-11ea-89e0-a6cfd07d3b5e.PNG)

**Comment by Conduitry** [comment]
This program manages its own portable copy of Chromium. I would expect that whatever version you have installed in Program Files would be completely unrelated, and untouched by chrlauncher.

**Comment by henrypp** [comment]
@Conduitry completely agree!
