### ISSUE TITLE
Command line with spaces bug

### ISSUE THREAD

**Issue by BIOS999** [henrypp/chrlauncher#186]
Try to run chrlauncher with spaced and quoted argument:
chrlauncher.exe --profile-directory="Profile 5"

And chrome will get it as:
chrome.exe --profile-directory=Profile 5

Because _CommandLineToArgvW_ unquotes arguments (main.cpp line 245)
But we don't quote again on arguments building (main.cpp line 291)

Let's add quotting with replacing line 291:
`_r_str_cat (pbi->args, _countof (pbi->args), arga[i]);`
TO
```
WCHAR arg[128] = {0};
arg[0] = UNICODE_NULL;
_r_str_copy (arg, _countof (arg), arga[i]);
_r_str_replace (arg, L"\"", L"\\\"");
_r_str_cat (pbi->args, _countof (pbi->args), L"\"");
_r_str_cat (pbi->args, _countof (pbi->args), arg);
_r_str_cat (pbi->args, _countof (pbi->args), L"\"");
```

Additionally, it is good to add check for space and quote-symbol present in processing argument.

P.S. Sorry for mistake, I am on way, so I can't to check a code

**Comment by azev** [comment]
Same issue here.

`chrlauncher.exe --user-agent="Mozilla/5.0 (Linux; Android 8.0.0; SM-G960F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36"`

Will run:
`chrlauncher.exe --user-agent=Mozilla/5.0`

Which fails because will report only `Mozilla/5.0` to websites because chrlauncher is not passing it along with quotes.

**Comment by azev** [comment]
To fix this issue I suggest chlauncher to transform **backquotes** into **double quotes**:

chrlauncher.exe --user-agent=\`Mozilla/5.0 (Linux; Android 8.0.0; SM-G960F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36\`

chrlauncher.exe --user-agent="Mozilla/5.0 (Linux; Android 8.0.0; SM-G960F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36"
