### ISSUE TITLE
No issue

### ISSUE THREAD

**Issue by narcolepticinsomniac** [henrypp/chrlauncher#19]
I stumbled on to this utility, and I just wanted to say thanks because it's great. Also your "about me" page is hilarious. Keep up the good work!

**Comment by Phoenix1747** [comment]
I have to agree with you - this is just awesome work. Everything runs smoothly and as expected. Also there is no additional crap like ads or "sell-your-soul-for-this-free-software" thingy.

His "about me" page really is amusing but true :D

**Comment by woolyss** [comment]
@narcolepticinsomniac: your "about me" page is hilarious

I agree ;)
http://www.henrypp.org/about

**Comment by henrypp** [comment]
is not hilarious, but honest

**Comment by Phoenix1747** [comment]
@henrypp so true

**Comment by woolyss** [comment]
@henrypp: Yes! We know that but it is fun to write this. I completely agree with you ;)
