### ISSUE TITLE
ChromiumType is ignored

### ISSUE THREAD

**Issue by antgustech** [henrypp/chrlauncher#197]
I wanted to use this launcher for launching and updating ungoogled-chromium. To do this, I changed the config file to

ChromiumType=ungoogled-chromium

And ran the launcher again. However it is still configured as dev-official (64-bit)

**Comment by henrypp** [comment]
chrlauncher is only update configured builds by checking version, nothing more.

solution:
- just cleanup you `ChromiumDirectory` and start chrlauncher again, it will download `ungoogled-chromium`.
