### ISSUE TITLE
Missing repository [32 bit / Stable / Codecs / Nosync]

### ISSUE THREAD

**Issue by Franzz** [henrypp/chrlauncher#20]
Hello,

I am getting this error message when starting chrlauncher for the first time with the following settings (ok with default settings):
- ChromiumArchitecture=0
- ChromiumType=stable-codecs-nosync
- Flash Player activated

![image](https://cloud.githubusercontent.com/assets/298765/16689425/37f07fc6-4523-11e6-9683-be32d7907b70.png)

**Comment by henrypp** [comment]
[sync/nosync builds]([](https://github.com/henrypp/chromium)) has no 32-bit builds!
