### ISSUE TITLE
update not working

### ISSUE THREAD

**Issue by R44D44** [henrypp/chrlauncher#204]
[(https://chromium.woolyss.com/api/v3/?os=windows&bit=%d&type=%s&out=string)]
seems not a valid dl link anymore

**Comment by henrypp** [comment]
> seems not a valid dl link anymore

why is that?

**Comment by R44D44** [comment]
the updater is not updating anymore to the latest version. that would be v. 4873.0 according to the updater. i am ising x64 only btw.

so i fgured the link pasted into the browser would dl the update but it does not.

Am 6. Februar 2022 18:20:50 MEZ schrieb henrypp ***@***.***>:

**Comment by henrypp** [comment]
what `chromiumtype`?

**Comment by R44D44** [comment]
the default

Am 6. Februar 2022 18:56:18 MEZ schrieb henrypp ***@***.***>:

**Comment by henrypp** [comment]
latest is 100.0.4874.0, update is not checked because `ChromiumCheckPeriod`
