### ISSUE TITLE
UPDATE for New Releases on chromium.woolyss.com

### ISSUE THREAD

**Issue by Alex313031** [henrypp/chrlauncher#208]
Hello, I'm the maintainer of Thorium, and currently have avx and avx2 releases up on chromium.woolyss.com

I had someone making an issue here > https://github.com/Alex313031/Thorium-AVX2/issues/6 and am making an issue as I told him I would to alert you to new releases.

On top of that, there have been some releases removed and added regardless for win and other platforms. 

Thanks for your work, I use alot of your programs on my win 7, 10, and 11 machines, namely memreduct, errorlookup, freeshooter, matrix screensaver, and iplookup. They all provide functionality I wasn't able to find in any other program, and they are open source so yay.

**Comment by Technetium1** [comment]
I do not see an associated commit for closing this, so I'm assuming that this isn't going to happen.
