### ISSUE TITLE
Pepper Flash Player plugin update

### ISSUE THREAD

**Issue by skarsgal** [henrypp/chrlauncher#21]
Hi,
the latest version of Pepper Flash plugin is 22.0.0.192 and You can retrieve it from:
- PCR's notepad: https://notepad.patheticcockroach.com/4029/flash-player-12-for-portable-browsers-32-and-64-bits/
- download page: http://uploaded.net/file/figahf6e

**Comment by henrypp** [comment]
Hi,
You can update it himself!

LInk:
http://effect8.ru/soft/media/adobe-flash-player-portable.html
