### ISSUE TITLE
System migration

### ISSUE THREAD

**Issue by Chaython** [henrypp/chrlauncher#211]
When I clean installed windows, chromium reset all settings [removed all saved passwords and extensions]
It didn't only happen with this launcher but with Vivaldi etc as well.
Any idea why that happened, or to recover the previously saved passwords aside from password resets?

**Comment by spdfnet** [comment]
You might be facing this issue:
https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/36

Nothing to do with this repo though.
