### ISSUE TITLE
Windows Defender Anti Virus has flagged chrome.exe

### ISSUE THREAD

**Issue by Ep0chalypse** [henrypp/chrlauncher#212]
I've been using this for a while and have never had an issue, however today it updated from and then windows defender anti-virus flagged chrome.exe as a severe threat.

![defender screenshot](https://i.imgur.com/1okqABF.png)

```
Trojan:Script/Wacatac.B!ml
file: C:\Users\User\Downloads\chrlauncher\64\bin\chrome.exe
This program is dangerous and executes commands from an attacker.
```

I uploaded chrome.exe to virus total:
https://www.virustotal.com/gui/file/046c75419035d330e8fc7f1dd2f1869065f9c722eaa2e8237ac62e39aa197eba

I also uploaded chrome.dll:
https://www.virustotal.com/gui/file/91fcc88604ad9ba5868a7efb8b18dfbc39f988112f8f151e99b61dbbbfb54e49

**Comment by henrypp** [comment]
Why this issue is connected with chrlauncher?
