### ISSUE TITLE
Proxy setting seems no longer work after upgrading to 2.6.0

### ISSUE THREAD

**Issue by shunf4** [henrypp/chrlauncher#213]
Proxy setting seems no longer work after upgrading to 2.6.0.

2.5.7 is fine.

**Comment by henrypp** [comment]
You won't know about `ms-settings:network-proxy`?

**Comment by shunf4** [comment]
> You won't know about `ms-settings:network-proxy`?

I knew it. So the feature mentioned in #108 was removed?

**Comment by henrypp** [comment]
yes

**Comment by jack980517** [comment]
> You won't know about `ms-settings:network-proxy`?

How about you stop being so aggressive? As of 80bbd02, "Set proxy configuration for a chrlauncher" is still linked under the FAQ section of README.md. There is no indication that it has been removed. Apart from this issue (#213) there's no way to know that the option has been removed. It's not even mentioned in 2.6 release notes.

Also, I'm on Win7 SP1 (which, according to the 2.6 release notes, *is* supported), and IE proxy settings didn't work either. I get the same 0x00002EE2 error (which afaik means a timeout) whether the `Proxy` ini option or IE proxy settings are set, or both.

But I don't care any more as I won't be using chrlauncher after seeing this issue.
