### ISSUE TITLE
[Bug] Programmatically calling chrome.exe with --profile-directory=Default doesn't works.

### ISSUE THREAD

**Issue by Rexadev** [henrypp/chrlauncher#221]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

Latest Marmaduke

### Windows version

Windows 10 21H1

### Steps to reproduce

chrome.exe needs to launched from chrlauncher. Can't launch incognito in a specific profile.
https://github.com/macchrome/winchrome/issues/86

### Expected behavior

--

### Actual behavior

`...\chrome.exe --profile-directory=Default -incognito opens in a new profile`
`...\chrlauncher.exe --profile-directory=Default -incognito doesn't work`

 --profile-directory=Default doesn't make a difference

--incognito instead of  -incognito doesn't make a difference

`...\chrlauncher.exe  --profile-directory=Default  --incognito` doesn't work

`...\chrome.exe  --profile-directory=Default  --incognito` opens in a new profile
chrome://version/ in that window shows C:\Users\User*\AppData\Local\Chromium\User Data\Default
while my portable Marmaduke chromium shows-`C:\...\chrlauncher-win64-stable-ungoogled\profile\Default`

--

**Comment by MINORITYmaN** [comment]
is anything wrong with `...\chrlauncher.exe --guest` or why you don't give it a try?

btw, i'm using this in the `chrlauncher.ini`:
`ChromiumCommandLine=--flag-switches-begin --user-data-dir=..\profile --no-default-browser-check --flag-switches-end --guest` and it does what i expect.

**Comment by Rexadev** [comment]
> ChromiumCommandLine=--flag-switches-begin --user-data-dir=..\profile --no-default-browser-check --flag-switches-end --guest

https://www.reddit.com/r/foobar2000/comments/112smvm/how_to_use_foo_run_to_open_incognito_in_chromium/

**Comment by henrypp** [comment]
Default is not a directory.

**Comment by Rexadev** [comment]
![image](https://user-images.githubusercontent.com/62152714/220332023-29f335a2-fe13-46a1-bf5f-898ce8d17776.png)

**Comment by henrypp** [comment]
Maybe because it ia not exiting, try create it yorself.

**Comment by Rexadev** [comment]
@henrypp 
Should I use -
`...\chrome.exe --profile-directory=Default -incognito` opens in a new profile
or

`...\chrlauncher.exe --profile-directory=Default -incognito`  doesn't work

**Comment by Rexadev** [comment]
@MINORITYmaN 

https://www.reddit.com/r/foobar2000/comments/1180ppq/how_to_use_foo_run_to_open_incognito_in_chromium/

**Comment by MINORITYmaN** [comment]
> @MINORITYmaN
> 
> https://www.reddit.com/r/foobar2000/comments/1180ppq/how_to_use_foo_run_to_open_incognito_in_chromium/

"Sorry, this post was removed by Reddit's spam filters."
still no changes to me, i cant see the post. only the redit bot message.

but henry is right, take a look at the vars used, default is not directory but the profile, if is does not exists it will be created.
the profile dir var decides, where the profiles are stored/red from, for example i store my temp profiles on a ram disk, this makes stuff run fast as heck.

**Comment by Rexadev** [comment]
How to use foo_run to open Incognito in Chromium Portable?

Browser - [Chromium UnGoogled x64 Portable Marmaduke](https://chromium.woolyss.com/#:~:text=ungoogled%0A%0A%0A%0Awidevine%0A%0Aall%2Dcodecs%2B%0A%0A%0Awin64-,Portable,-%E2%80%A2%20Archive%20%E2%80%A2%20Installer)

Run Service Command -

`C:\chrlauncher-win64-stable-ungoogled\chrlauncher 2.5.7 (64-bit).exe ChromiumCommandLine=--flag-switches-begin --user-data-dir="C:\chrlauncher-win64-stable-ungoogled\profile" --incognito --profile-directory=C:\chrlauncher-win64-stable-ungoogled\profile\Default --flag-switches-end" https://en.wikipedia.org/w/index.php?go=Go&search=$replace(%title%-%artist%, ,+)`

I used the command above in foo_run and it doesn't work


# Also See -

https://peter.sh/experiments/chromium-command-line-switches/

All Portable Chromium Builds use - https://github.com/henrypp/chrlauncher/


@MINORITYmaN

**Comment by henrypp** [comment]
It is really stupid placing chromium at drive C: `C:\chrlauncher-win64-stable-ungoogled\chrlauncher`. It requiring root access, and you do not have it. Place this shit in another folder.

**Comment by Rexadev** [comment]
Actually I have it in `C:\Apps\chrlauncher-win64-stable-ungoogled\chrlauncher`
@henrypp

**Comment by Rexadev** [comment]
@henrypp 
Actually I have it in C:\Apps\chrlauncher-win64-stable-ungoogled\chrlauncher

**Comment by Rexadev** [comment]
https://www.reddit.com/r/foobar2000/comments/y1gfxt/how_to_open_foo_run_links_in_nondefault_browser/
@MINORITYmaN

**Comment by Rexadev** [comment]
@henrypp 
Should I use -
`...\chrlauncher.exe  --incognito` doesn't work
or
`...\chrome.exe --incognito` opens in a new profile

**Comment by Rexadev** [comment]
> is anything wrong with `...\chrlauncher.exe --guest` or why you don't give it a try?

![image](https://user-images.githubusercontent.com/62152714/232206966-cde9b442-904c-4174-9081-dd26c95c0c00.png)

**Comment by MINORITYmaN** [comment]
i give you some hints, this way you will get some stuff right and understand why some thing are happening.

- problem with your paths and file names / escaping **spaces**
https://www.howtogeek.com/694949/how-to-escape-spaces-in-file-paths-on-the-windows-command-line/

- powershell console makes things a bit harder for you, so take a look at **strings** inside powershell
https://learn.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-string-substitutions?view=powershell-7.3#format-string

- powershell and exe file + their paths
- https://www.technewstoday.com/how-to-run-exe-in-powershell/

one final note, **if you change file paths and foldernames**,
be sure you know the basics behind the points i mentioned above
because you have multiple small issues to solve first.

**Comment by Rexadev** [comment]
![image](https://user-images.githubusercontent.com/62152714/235302020-000d258f-e390-44fc-b2aa-8134a57411dd.png)

**Comment by Rexadev** [comment]
Question Should It be-
`...\chrlauncher.exe  --incognito` doesn't work
or
`...\chrome.exe --incognito` opens in a new profile

@henrypp @MINORITYmaN

**Comment by MINORITYmaN** [comment]
The spaces inside the path and file name, kinda forced you thinking it will work just putting the path and the exe in separate DoubleQuotes (which wont work).
look my working examples in CMD
```
cd "C:\Users\user\Downloads\chrlauncher-2.6-bin\chrlauncher\64\"
"chrlauncher 2.5.7 (64-bit).exe"
```
```
cd "C:\Users\user\Downloads\chrlauncher-2.6-bin\chrlauncher\64\" && "chrlauncher 2.5.7 (64-bit).exe"
```
___
this works too, but you will see, why this is not the best way.
```
"C:\Users\user\Downloads\chrlauncher-2.6-bin\chrlauncher\64\chrlauncher 2.5.7 (64-bit).exe"
```
___
**chrlauncher.ini**
`ChromiumCommandLine=--flag-switches-begin --user-data-dir=..\profile --no-default-browser-check --flag-switches-end --guest`
if you need extensions in incognito mode, use `--incognito`
if you dont need extensions in incognito mode, use `--guest`
btw: https://superuser.com/questions/1234130/what-is-the-difference-between-guest-and-incognito-modes-of-chrome-browser

**Comment by Rexadev** [comment]
No errors but not opening
![image](https://github.com/henrypp/chrlauncher/assets/62152714/b5934e27-238e-4923-a9f3-015e521e1fca)
I am on Windows 11 User Account
@MINORITYmaN

**Comment by Rexadev** [comment]
> this works too, but you will see, why this is not the best way.
"C:\Users\user\Downloads\chrlauncher-2.6-bin\chrlauncher\64\chrlauncher 2.5.7 (64-bit).exe"

That would be a problem I want to use it with foo_run (foobar2000)

**Comment by Rexadev** [comment]
> if the last approach works and you dont get any path problems, then you can go with this.

chrome not openig

**Comment by MINORITYmaN** [comment]
> chrome not openig

chrome or chrlauncher?
it makes a big difference what you are launching first.
having chrome or chrlauncher as default browser makes a difference too (there is a reason why `SetDefaultBrowser.bat` exists).
your issue title says about `chrome.exe` but were are here in `henrypp/chrlauncher`.
that's a reason why it's getting confusing - with no offense,

further you should verify if you:

To integrate `henrypp/chrlauncher` with `foo_run` in Foobar2000, you can follow these steps:

1. Download and extract `henrypp/chrlauncher` from the official repository.

2. Launch `chrlauncher.exe` and configure it as per your requirements. This includes setting the desired version of Chromium and other options.

3. Once chrlauncher is set up and a portable Chromium binary is downloaded, navigate to your Foobar2000 installation folder.

4. Inside the Foobar2000 folder, locate the `user-components` folder. If it doesn't exist, create it.

5. Download the `foo_run` component (a DLL file) and place it in the `user-components` folder.

6. Launch Foobar2000 and go to the "Preferences" menu by pressing `Ctrl+P` or selecting it from the "File" menu.

7. In the Preferences window, navigate to "Components" under the "Advanced" section.

8. Locate `foo_run` in the list of components and click on it to select it.

9. Click on the "Configure" button to open the `foo_run` configuration window.

10. In the `foo_run` configuration window, specify the path to `chrlauncher.exe` and any desired parameters. For example:

   Executable: [path_to_chrlauncher]\chrlauncher.exe
   Parameters: --guest

11. Click "OK" to save the configuration.

12. Close the Preferences window.

Now, when you use `foo_run` to open a URL or launch a web-based application in Foobar2000, it should utilize `chrlauncher` with the specified parameters to open the URLs in the portable Chromium browser downloaded by `chrlauncher`.

**Comment by Rexadev** [comment]
chrlauncher

@MINORITYmaN

**Comment by henrypp** [comment]
Still cant understand, why this issue is for a launcher, because launcher is only creating process with specified arguments, and cant do anything like described in this shit issue (and nothing else in cfg cant do this).

Maybe trying to check your configuration can help?

**Comment by Rexadev** [comment]
I am able use 
`.\chrome.exe ChromiumCommandLine=--flag-switches-begin --user-data-dir=..\profile --no-default-browser-check --flag-switches-end --incognito`
When chrome is launched  in default profile with chrlauncher.
But earlier I was trying to run command with ChromiumCommandLine= for chrlauncher and that didn't work.

**Comment by Rexadev** [comment]
> Still cant understand, why this issue is for a launcher, because launcher is only creating process with specified arguments, and cant do anything like described in this shit issue (and nothing else in cfg cant do this).
> 
> Maybe trying to check your configuration can help?

https://github.com/macchrome/winchrome/issues/86

**Comment by Rexadev** [comment]
@henrypp @MINORITYmaN solved. It was not a launcher issue as said by marmaduke in https://github.com/macchrome/winchrome/issues/86
