### ISSUE TITLE
[Bug] Download Fails

### ISSUE THREAD

**Issue by lucas75018** [henrypp/chrlauncher#222]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

2.6

### Windows version

Windows 10 Enterprise [ Version: 10.0.19042 Release: 2009 ]

### Steps to reproduce

Starting the launcher ...
Shows
![image](https://user-images.githubusercontent.com/23362949/199014851-52b192e4-d286-4b7f-86c0-2aadd1843803.png)

Clicking on "Download update"
Show
![image](https://user-images.githubusercontent.com/23362949/199015349-b7444b5c-4426-48e2-bbfe-5ea846a4cb28.png)

### Expected behavior

Downloading of the latest version

### Actual behavior

Error ... see log below ...

The issue started with the latest Chrome version for me (guessed)!

```
[v.2.4.3](https://github.com/henrypp/chrlauncher/releases/tag/v.2.4.3)
fixed tls 1.2 certificates recognition (issue https://github.com/henrypp/chrlauncher/issues/95)
```
But that should be fixed... :-/

I **can** download ...
https://github.com/macchrome/winchrome/releases/download/v107.5304.88-M107.0.5304.88-r1047731-Win64/ungoogled-chromium-107.0.5304.88-1_Win64.7z
in all of my browsers and sucessfully unpack the 7Z archive.

I could not spot any flag to get more debugging in the source code to get more information.
Using ProcMon did not help either to identify the cause. :(

Side note ... we are using ZScaler that intecepts most of our traffic using a Root CA that is not part of some official trust store.

Thanks and regards

### Logs

"Error","‎31.‎10.‎2022 ‏‎13:09:16","_app_downloadupdate","0x00002EFD","https://github.com/macchrome/winchrome/releases/download/v107.5304.88-M107.0.5304.88-r1047731-Win64/ungoogled-chromium-107.0.5304.88-1_Win64.7z","2.6","10.0 build 19042"

**Comment by henrypp** [comment]
You have a problem.
> A connection with the server could not be established
