### ISSUE TITLE
[Question] Is it possible to donwngrade to pre-110 version?

### ISSUE THREAD

**Issue by MaggotHATE** [henrypp/chrlauncher#228]
The 110 chromium update made it unusable on Windows 8.1, as promised earlier, but I didn't expect chrlauncher to automatically downdload an unusable version and lock me out of the browser. Is it possible to download and launch an exact version of chromium through chrlauncher, or it there a compatible manual download for the latest 109 version?

---

App version: last working: 109.0.5414.120
Windows version: 8.1

**Comment by rextheleopard** [comment]
You can download 109.0.5414.120 ([x32](https://github.com/Hibbiki/chromium-win32/releases/tag/v109.0.5414.120-r1070088), [x64](https://github.com/Hibbiki/chromium-win64/releases/tag/v109.0.5414.120-r1070088)) and disable autoupdate (ChromiumCheckPeriod=0).

**Comment by MaggotHATE** [comment]
> You can download 109.0.5414.120 ([x32](https://github.com/Hibbiki/chromium-win32/releases/tag/v109.0.5414.120-r1070088), [x64](https://github.com/Hibbiki/chromium-win64/releases/tag/v109.0.5414.120-r1070088)) and disable autoupdate (ChromiumCheckPeriod=0 in chrlauncher.ini).

That's not what this the issue is about, though. Autoupdates worked fine and were necessary while new versions were still compatible. If it is possible to detect which system the user runs, it makes sense to at least consider checking it. 

The official support for Win10 is slowly approaching it's end, and MS seems to be more aggressive in pushing Win11. This can potentially result in many more similar cases, but for much larger Win10 userbase.

**Comment by henrypp** [comment]
you can download it yourself
