### ISSUE TITLE
[Feature] Add the possibility of launching a post-update exe/batch

### ISSUE THREAD

**Issue by uazo** [henrypp/chrlauncher#231]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

2.5.7.0

### Problem you are trying to solve

Configuration of chromium networking service sandbox

### Suggested solution

meanwhile thank you!

I was wondering if it would be possible to add an option in the ini that would allow the launch of a program (specifically I was thinking of a batch file, but I think it's irrelevant) after each update made with the user's current permissions.
I'm using your program to auto-update https://github.com/uazo/bromite-buildtools would come in handy when configuring the chromium network service sandbox.

more details https://github.com/uazo/bromite-buildtools/issues/51

**Comment by henrypp** [comment]
@E021ntox mb

**Comment by henrypp** [comment]
@E021ntox u even dont need to open sln, just clone repo and run vuild_vc.bat (with installed [vs community](https://visualstudio.microsoft.com/vs/community/) or pro)

**Comment by henrypp** [comment]
@E021ntox wat wont worked? code does not say anything

**Comment by henrypp** [comment]
@E021ntox it wont connect or what?

**Comment by henrypp** [comment]
@E021ntox and how u decided it?

**Comment by henrypp** [comment]
thats because u specified just address without scheme, i fixed it, check it in 5 minutes and re-pull routine again

**Comment by henrypp** [comment]
@E021ntox http\https does not matter. if u compiled, then its needed to work again. what not worked?

**Comment by henrypp** [comment]
@E021ntox now it is complete fixed

**Comment by henrypp** [comment]
@E021ntox aga, it is not finished to release

**Comment by henrypp** [comment]
@E021ntox done!
