### ISSUE TITLE
[Bug] ungoogled-chromium confusion

### ISSUE THREAD

**Issue by PF4Public** [henrypp/chrlauncher#233]
@henrypp Please make it so that `ungoogled-chromium` option does actually download `ungoogled-chromium`. And not any other binary.

If that is not possible, please make it clear, that the resulting binary is not ungoogled-chromium.

The problem is that users are using binaries we have no control of and file issues for ungoogled-chromium that we cannot possibly fix.

**Comment by henrypp** [comment]
not possible
