### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by painsucker-0** [henrypp/chrlauncher#236]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

119.0.6045.106

### Windows version

10

### Steps to reproduce

Many websites, are not able to play videos.
for example:

yugenanime.tv (using the external player)
(Cannot play the video and shows error code 102630)
with internal player it just remains blank

instagram.com
(Just shows cannot play video)

### Expected behavior

It should be able to play the videos without any problems.
However, youtube videos play normally. No issues.

### Actual behavior

Yugenanime
Internal player:
![image](https://github.com/henrypp/chrlauncher/assets/119797321/5cd8be0d-291d-44f9-be49-0d2c04a32afa)

External Player:
![image](https://github.com/henrypp/chrlauncher/assets/119797321/51991ed6-16a6-40b6-a728-0c0e862bb600

Instagram:
![image](https://github.com/henrypp/chrlauncher/assets/119797321/581dee77-e0a3-4685-900f-ec2a958c39d5)

**Comment by henrypp** [comment]
and why you tell me?

**Comment by painsucker-0** [comment]
Wonder why it posted here. Supposed to be in Cromite, probably Github glitches out or I made a mistake. Apologies.
