### ISSUE TITLE
Uninstall? 

### ISSUE THREAD

**Issue by digital-carver** [henrypp/chrlauncher#25]
Hi, 
How do I uninstall the Chromium installed this way? Would just deleting the bin/ and profile/ directories do, or is there a better way to do it?

**Comment by henrypp** [comment]
import `RegistryCleaner.reg` into registry and delete chrlauncher folder.

**Comment by mauricecaaaaaben** [comment]
henry, I believe he meant Chromium itself, not chrlauncher... digital-carver just deleting the bin folder gets rid of Chromium and deleting the profile folder removes extensions, themes, settings etc. You can effectively uninstall by deleting those folders yes

**Comment by henrypp** [comment]
@mauricecaaaaaben
i'm not a Chromium author.
