### ISSUE TITLE
[Question] Is there any way to get it to just launch Chromium from a shortcut without showing chrlauncher window?

### ISSUE THREAD

**Issue by BlohoJo** [henrypp/chrlauncher#253]
Chrlauncher is what is used to start the [portable version](https://chromium.woolyss.com/f/chrlauncher-win64-stable-codecs-sync.zip) of the [Hibbiki build](https://github.com/Hibbiki/chromium-win64) of Chromium. (Available from https://chromium.woolyss.com/)

The only way to launch Chromium in this build is by running chrlauncher, which starts the chrlauncher application, then the user has to select File -> Start to actually launch Chromium.

Is there a way to get chrlauncher to just launch the browser without showing the chrlauncher application window and requiring the user to select File -> Start first?

---

App version: <2.6>
Windows version: <19041.1415>

**Comment by emidaniel** [comment]
https://github.com/henrypp/chrlauncher/issues/96#issuecomment-439294915

**Comment by henrypp** [comment]
~~~ini
ChromiumBringToFront=false
ChromiumWaitForDownloadEnd=false
~~~
