### ISSUE TITLE
Can't get it to work with versions from HenryPP

### ISSUE THREAD

**Issue by abrownk** [henrypp/chrlauncher#26]
When I'm on http://chromium.woolyss.com/, I can just download the installer and install Chromium (most importantly, complete with things such as Widevine).  When I try to use chrlauncher as a utility to update said install, it instead installs a separate instance of Chromium, without my profile, or things like Widevine enabled or working.  I have played around with the .ini and cannot figure out how to get this seemingly useful application to do what I want to do: update my current installation from the installer found at http://chromium.woolyss.com/ (where this utility is advertised in the first place).

Am I not changing something correctly in the ini file?  Help would be appreciated because I would like to use this.

**Comment by henrypp** [comment]
Set `ChromiumDirectory` parameter to installed Chromium directory and set`ChromiumType` to `dev-official` . If you can use your default profile from %APPDATA% directory remove `--user-data-dir=..\profile` from `ChromiumCommandLine`
