### ISSUE TITLE
Feature request: Force an update check by holding a certain key

### ISSUE THREAD

**Issue by mauricecaaaaaben** [henrypp/chrlauncher#30]

**Comment by woolyss** [comment]
To force an update of Chromium browser, set `ChromiumCheckPeriodLast=0` in the **chrlauncher.ini** file

**Comment by henrypp** [comment]
No, in next version i add command line argument to force update check!

**Comment by woolyss** [comment]
ok henrypp. Thanks.

**Comment by mauricecaaaaaben** [comment]
that's what i'd been doing before woolyss but its a bit of a pia... btw, do you have any plans to switch to https anytime soon?

**Comment by woolyss** [comment]
@mauricecaaaaaben: >do you have any plans to switch to https anytime soon?
Yes. I will put a Let's Encrypt SSL/TLS certificate on chromium.woolyss.com. The problem is there is already a certificate on the cluster. https://www.ssllabs.com/ssltest/analyze.html?d=chromium.woolyss.com

**Comment by henrypp** [comment]
[How to force check for an update every chrlauncher start?](https://github.com/henrypp/chrlauncher/issues/92#issuecomment-343274418)
