### ISSUE TITLE
stable-codecs-nosync downloading a build with sync?

### ISSUE THREAD

**Issue by mauricecaaaaaben** [henrypp/chrlauncher#31]
http://i.imgur.com/uLH8RJM.png

**Comment by woolyss** [comment]
No. You see the popup windows but you cannot sign in --> So no sync.

Nik the developer explains that at http://chromium.woolyss.com/#comment-1239
> no it doesn't, only the icon is shown because from v53 google change the UI code.

**Comment by mauricecaaaaaben** [comment]
Well fuck, they remove the annoyance of the issue with the title bar buttons sticking and then they add another by not being able remove this button now :/
