### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Phoenix1747** [henrypp/chrlauncher#32]
![translate](https://cloud.githubusercontent.com/assets/17517687/18556790/c98377de-7b6c-11e6-812a-dd611cc9e768.png)
*"Are you want to close application?"*
I think you have to fix something in your translation, no matter how :stuck_out_tongue: ( ****cough****  https://github.com/henrypp/chrlauncher/pull/29)

**Comment by henrypp** [comment]
srsly?

**Comment by Phoenix1747** [comment]
Sorry, I don't know what's wrong with your local import but there must be a way to fix this.

**Comment by henrypp** [comment]
my misstake. fixed!
