### ISSUE TITLE
[Feature Request] Add support for ungoogled-chromium

### ISSUE THREAD

**Issue by rodneyrod** [henrypp/chrlauncher#33]
https://github.com/Eloston/ungoogled-chromium

**Comment by woolyss** [comment]
We (Nik and me) know these patches for few months.
But Nik will do not compile Chromium with these patches.

1) First reason:
Check the Nik answer at http://chromium.woolyss.com/?all=1#comment-995
(this link will display ALL comments. It can be slow to display)

2) Second reason:
Nik and me want to keep "Chromium as Chromium".
It means that there are other builds using similar patches. So why to redo another browser?
Brave Browser, Comodo Dragon, SRWare Iron, Epic Browser...
More at http://chromium.woolyss.com/#browsers

**Comment by henrypp** [comment]
@woolyss, so question to you: can you add possibility to your api for download ungoogled chromium from chrlauncher?

**Comment by woolyss** [comment]
@henrypp ungoogled-chromium is not a web browser. It is only a set of configuration flags, patches, and custom scripts. This set must be applied before to compile Chromium.

**Comment by rodneyrod** [comment]
@woolyss Thank you for this, I know it's outside the scope of your project, but it would greatly assist users in deploying ungoogled-chromium on their systems, especially those who need a portable setup.

**Comment by woolyss** [comment]
Please, can you test the new chromium 64-bit with "ungoogled-chromium" patches?
http://chromium.woolyss.com/#windows-64-bit-test-nik

**Comment by leeoniya** [comment]
cool! i'll test as well.

any plans on eventually building ungoogled dev versions? (55.x)

**Comment by woolyss** [comment]
@leeoniya: > dev versions? (55.x)
In short, patches are for stable versions.
https://github.com/Eloston/ungoogled-chromium/blob/master/version.ini

More info:
Some of the patches are not working because they are for GYP build system (fix-building-without-one-click-signin.patch and others). Nik, our developer uses GN build system, the new one! ;)

**Comment by leeoniya** [comment]
couple things i've run into so far:

- Chrome extensions are not installable from store (there's not Add to Chrome button), eg [1]. For uMatrix and uBlock Origin, i can install them i developer mode if i download & unpack them from the github repos, but I imagine most extensions dont provide an easy way to grab these zips/crxs/whatever. Also, it means i'm on my own for keeping these extensions constantly updated which could be a security vuln.

- Clicking "Get more extensions", at the bottom of the extensions page which points to https://chrome.9oo91e.qjz9zk/webstore/category/extensions?hl=en-US results in "Blocked attemptd request to: ..."

- The following are pre-installed and appear to be non-removable from the extension manager: Bookmark Manager, Chromium PDF Viewer (isn't this a binary, closed-source blob?), CryptoTokenExtension.

[1] https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en

**Comment by woolyss** [comment]
@leeoniya,

> Chrome extensions are not installable from store
You can use other ways: http://chromium.woolyss.com/#external-extension-installation

>  Chromium PDF Viewer [...] closed-source?
No. It is PDFium: https://pdfium.googlesource.com/pdfium/

**Comment by leeoniya** [comment]
> You can use other ways: https://chromium.woolyss.com/#external-extension-installation

It would be really useful if chrlauncher could do most (if not all) of this for me (if i enable some extension-auto-update flag). It's simply not practical to do this manually using third-party utils to keep everything updated.

> No. It is PDFium: https://pdfium.googlesource.com/pdfium/

Still, i should be able to choose another viewer like PDF.js, so it should be removable or at least disable-able? A build without WideVine would be welcome, too.

Do all these extensions already exist in normal Chromium but are hidden from the list because they're "Managed" and ungoogled just unhides them and shows you the reality?

**Comment by woolyss** [comment]
> if chrlauncher could do most

I do no know if **henrypp** will improve chrlauncher in this direction.

On ungoogled-chromium, you cannot remove default addons.
https://i.imgur.com/SrrF8Dy.png

But you can disable **Chromium PDF Viewer** on chrome://plugins
Install another PDF viewer now! ;)

Tested on:
32-bit version: https://github.com/Eloston/ungoogled-chromium/releases/tag/53.0.2785.116-1
64-bit version: https://chromium.woolyss.com/#windows-64-bit-test-nik
Same result!

ungoogled-chromium is not our (nik and me) project. So, it is difficult to help you ;)
**Eloston** plan to do a 64-bit version: https://github.com/Eloston/ungoogled-chromium/issues/62#issuecomment-251503958

**Comment by fbis251** [comment]
ungoogled-chromium has received a lot of updates since October and it seems like there aren't any major issues with it anymore.

@woolyss would it be possible to add ungoogled-chromium to your site again to enable chrlauncher to auto update it?

**Comment by woolyss** [comment]
@fbis251 Yes. It is possible. I prepares that.

**Comment by fbis251** [comment]
@woolyss Don't mean to be a bother but have you had a chance to look at adding ungoogled-chromium?

**Comment by henrypp** [comment]
see 2.3

**Comment by woolyss** [comment]
@henrypp: Thank you very much Henry. You are the man! ;)

[ungoogled-chromium](https://github.com/Eloston/ungoogled-chromium) is now supported by the free and open-source [chrlauncher](https://github.com/henrypp/chrlauncher). 

So now chrlauncher can install, **automatically update** and launch Chromium and **ungoogled-chromium**.

All works nicely with your latest **chrlauncher v2.3**
https://github.com/henrypp/chrlauncher/releases

For info, API used for update: 

- 64-bit: https://chromium.woolyss.com/api/v3/?os=windows&bit=64&type=ungoogled-chromium&out=json
- 32-bit: https://chromium.woolyss.com/api/v3/?os=windows&bit=32&type=ungoogled-chromium&out=json

**Comment by magicgoose** [comment]
@woolyss it's only for windows™.

**Comment by KonoromiHimaries** [comment]
https://github.com/henrypp/chrlauncher/issues/33

**Comment by KonoromiHimaries** [comment]
https://github.com/henrypp/chrlauncher/issues/158
