### ISSUE TITLE
Flash plugin is not loading: "Couldn't load plugin."

### ISSUE THREAD

**Issue by waqas** [henrypp/chrlauncher#34]
I am using it with a Chromium 53 (32 bit) build from Nik. It shows plugin at chrome://plugins. But when I open website it shows "Couldn't load plugin." at the place of the Flash area.

**Comment by henrypp** [comment]
For flash player needed`--disable-component-update` commandline

`ChromiumCommandLine=--user-data-dir=..\profile --no-default-browser-check --allow-outdated-plugins --disable-component-update`

**Comment by waqas** [comment]
Thanks.
How can I stop this annoying warning?

![2016-10-13 20_38_44-chrlauncher](https://cloud.githubusercontent.com/assets/407/19356009/c391d490-9185-11e6-86a5-2beeeb35ca2a.png)

**Comment by henrypp** [comment]
@waqas, use 64-bit version of chrlauncher
