### ISSUE TITLE
Widevine problems

### ISSUE THREAD

**Issue by step21** [henrypp/chrlauncher#35]
With chrlauncher (thanks for it!) and different channels I so far did not find one where widevine support was working. The dlls are there, but chrome://components does not show widevine but says 'No components installed'. Do you know anything about this problem? I have poked around a bit but without any success so far, also went through comments on https://chromium.woolyss.com but no luck so far.
Any help appreciated.

**Comment by step21** [comment]
Could it be that widevine only works with 32 bit? I only tried 64 bit chrlauncher I think.

**Comment by woolyss** [comment]
Hello @step21 
Like you I do not see Widevine plugin listed at chrome://components or chrome://plugins on Nik builds with Sync and Widevine. We check that.

**Comment by step21** [comment]
Thanks @woolyss - removing `--disable-component-update` made the components show up under `chrome://components`. However, when clicking update, it said 'Not updated', so presumably it is up to date? When testing with Netflix I get 'Unexpected Error' (with UAgent set to Chrome)

**Comment by woolyss** [comment]
Thanks for feedback.
Is it always enabled? http://i.imgur.com/7c4ohdW.png

**Comment by step21** [comment]
It was not, but now I switched to this. However, it did not seem to make a difference. One other difference I noted, that it is not using the widevine shipped with chrlauncher/chromium but the path from a normal install.(I guess) (AppData\Local\Chromium\User Data\WidevineCdm\1.4.8.903\_platform_specific\win_x64\widevinecdmadapter.dll) In addition, I always start with --no-sandbox as otherwise all tabs crash. I cannot remember right now whether this was default in chrlauncher.ini or if I added it. Could this cause problems?

**Comment by woolyss** [comment]
> it is not using the widevine shipped with chrlauncher/chromium
Mine uses Widevine shipped with it (as you see in my last screenshot)

>  was default in chrlauncher.ini 
Check https://github.com/henrypp/chrlauncher/blob/master/bin/chrlauncher.ini

> --no-sandbox as otherwise all tabs crash.
Strange! I never use this flag. And tabs work nicely on my x64 chromium version, on win7.

**Comment by step21** [comment]
Thanks for these hints. I am not sure why my chrlauncher.ini is different, maybe it was different because I downloaded a more restricted/more free version first? (or I changed it)
My chromium command line is `ChromiumCommandLine=--user-data-dir="C:\Users\Florian\AppData\Local\Chromium\User Data" --no-sandbox --no-default-browser-check --allow-outdated-plugins --ppapi-out-of-process` and my update channel is `stable-codecs-sync`
Additionally, I have a directory called `~/bin` where I put programs that do not need an installer, but which I might want to have in `%PATH%`. I put only the 64 bit version of chrlauncher into that, and so the actual chrome is ~/bin/bin
When I try the Sintel test, it detects widevine (where you indicated in the screenshot) but the player reports `XHR status is "Precondition failed" (412), expected to be 200, ready state is 4.`
In firefox it works - but it also still uses Silverlight on Netflix, unless you switch UserAgent to Chrome.(this last part tested under Linux) 
Anyway, I guess the problem might be that the ChromiumCommandline references a different chrome - but I am not sure why that is. Maybe as I wanted to keep my profile?

**Comment by SyntaxErrol** [comment]
I have also never had Widevine work with these builds but I'd like it to. I tried to get to the bottom of the issue by starting from scratch and erasing any trace of Chromium on the drive. Downloaded the latest chrlauncher and dropped the "64" folder into Program Files as "Chromium". My preferred update channel is stable-codecs-nosync. Launching the launcher downloads and runs Chromium as expected, but contrary to 
>> it is not using the widevine shipped with chrlauncher/chromium

> Mine uses Widevine shipped with it (as you see in my last screenshot)

there's no trace of Widevine anywhere. And that I think has been the issue all along. I don't think I've ever seen any Widevine related files show up while trying to change the update channel or running a Widevine installer etc.

**Comment by pushrbx** [comment]
I tried to fiddle around with the problem and I've found that if you don't put your profiles folder on the system drive (C:) then the components won't load.
Just an example:
If you start chromium with command line flag `--user-data-dir=D:\Chromium\profile`   
then it won't load the components.
If you start it with
`--user-data-dir=C:\Users\username\Documents\chromium\profile`
everything is fine.
So I guess that this is some sort of a permission issue.
I'm using Windows 10.

**Comment by SyntaxErrol** [comment]
> @SyntaxErrol no-sync versions of chromium doesn't have widevine.

Well that would explain it but is this necessary? And furthermore, is this mentioned anywhere else? I would have suspected a closer coupling with codecs rather than sync.    
    
Changing my update channel to stable-codecs-sync did finally make some Widevine files appear in bin/ (although I could have sworn I tried it before) but still, nothing in chrome://components. I also tried moving the whole thing under my user profile to mitigate any permission issues that might exist under Program Files as well as specifying an absolute --user-data-dir path instead of ..\profile, to no avail.

**Comment by SyntaxErrol** [comment]
Jeez, I thought I finally figured it out for myself only to find I missed [woolyss' initial reply](https://github.com/henrypp/chrlauncher/issues/35#issuecomment-254550676).

> 1. Delete --disable-component-update in the **chrlauncher.ini** file.

was indeed what made something show up in about:components and finally, choosing a sync build ([thanks, pushrbx](https://github.com/henrypp/chrlauncher/issues/35#issuecomment-266161899)) made that include Widevine as well. And it works.

**Comment by SHJordan** [comment]
This really helped me... deleting the option and updating manually did the trick for what i wanted, netflix.

BUT i have some questions...

should i update any of these:

CRLSet
pnacl 
File Type Policies
Origin Trials
EV Certs CT whitelist
Signed Tree Heads

and if no, why not?

**Comment by henrypp** [comment]
2.3 fixed
