### ISSUE TITLE
User Profiles

### ISSUE THREAD

**Issue by snakyjake1** [henrypp/chrlauncher#36]
It seems the command line argument for user `--user-data-dir` and/or `--profile-directory` isn't working anymore.

Also noticed the Chromium Profile screen appears, which it didn't use to.  I also use the "stable-codecs-nosync" builds.  It specifically says "without the profile button", so not sure why I see a profile screen now.

I estimate I started to have this problem around the September 2016 time frame.

**Comment by henrypp** [comment]
#31

**Comment by coding-guy** [comment]
What's about this?

> It seems the command line argument for user --user-data-dir and/or --profile-directory isn't working anymore.

I have the same problem right now with version 1.9.4. When I specifiy the profile with `--profile-directory="Profile 1"` the browser starts with the latest profile closed. Not with the specified one.

**Comment by henrypp** [comment]
@coding-guy 

what about this:
1) use "--user-data-dir" instead"--profile-directory" **!IMPORTANT**
2) use right syntax? you may set relative path ("..\profile"), path with environment variable (%appdata%\profile) or full path (c:\profile).

**Comment by coding-guy** [comment]
Oh, this is a misunderstanding!
`--profile-directory` is used to force a certain profile to load when starting chromium.
