### ISSUE TITLE
Chromium flickering around

### ISSUE THREAD

**Issue by Phoenix1747** [henrypp/chrlauncher#39]
This is extremely annoying: I am using crlauncher with dev-codes-sync on Windows 10. 

Every so often chromium dissapears to show up after like half a second. That looks like flickering and is extremely annoying, because it sometimes kills a video or eg. a pdf document which i was reading.

**Comment by leeoniya** [comment]
same here, looks like recent `dev-codecs-nosync` build has some bug that glitches the ui

**Comment by Phoenix1747** [comment]
Closing this issue because it's been opened here: https://github.com/henrypp/chromium/issues/9
That's more suitable.
