### ISSUE TITLE
Pass URL from command line to Chromium

### ISSUE THREAD

**Issue by JustOff** [henrypp/chrlauncher#4]
Could you please add the ability to pass URL from command line to Chromium?

**Comment by henrypp** [comment]
Started from version 1.6 you can pass URL to Chromium as arguments:
`chrlauncher.exe /url "https://github.com/henrypp"`

**Comment by snakyjake1** [comment]
This feature would be useful so other applications can launch a URL.  But the application I'm working with doesn't like switches (https://github.com/QuiteRSS/quiterss).

**Comment by henrypp** [comment]
you can set "chrlauncher" as default internet browser, by "SetDefaultBrowser.bat" and in "quiterss" use "Default external browser"

**Comment by snakyjake1** [comment]
Having a "/url" command line switch doesn't work for my purpose.

I don't want Chromium to be my default browser (especially when I have multiple browsers and versions of browsers).

Therefore I took advantage of github and the generosity of henrypp and created a fork and made changes so I can launch from the command line with just a simple URL.  Thank you for this capability.
