### ISSUE TITLE
Button to Update or Not before Updating

### ISSUE THREAD

**Issue by Yamakasi** [henrypp/chrlauncher#46]
Hi,

It would be awesome if you are able to click "update" or "not now" when chrlauncher detects an update, this becuase it could happen you are on UTMS or so, bad connection and you just want to use Chromium instead of the latest version.

I hope you can add this and thanks for the great launcher!

Thanks,

Matt

**Comment by henrypp** [comment]
2.0 closed

**Comment by Yamakasi** [comment]
Thanks a lot!
