### ISSUE TITLE
Proxy Server?

### ISSUE THREAD

**Issue by butangmucat** [henrypp/chrlauncher#47]
I am currently in a certain country where the Internet traffic is censored, and I run a local Privoxy server combined with https://github.com/shadowsocks/shadowsocks-libev to gain access to certain blocked websites. My Windows OS is configured to use 127.0.0.1:8118 as a system proxy. However chrlauncher seems to ignore the setting as every day I do get a "no updates found message." The config file doesn't seem to have a section for proxy settings either. I would like to have support for proxy servers.

Edit: suddenly chrlauncher discovered an update, but seems to download at a very slow speed. Might need help to determine if it is going through my proxy.

**Comment by henrypp** [comment]
chrlauncher uses connection configuration from system. see inetcpl.cpl > "Connections" - > "Network Configuration"
