### ISSUE TITLE
Flash plugin does not load on 2.0.0

### ISSUE THREAD

**Issue by acaN** [henrypp/chrlauncher#48]
Hello!

I am using x64 versions of chrlauncher and Chromium.

Tried with different chrome binaries (stable and lkgr) and plugin versions(different x64 and even x32), but the result is still same:
![chrm](https://cloud.githubusercontent.com/assets/470280/22019518/f8fdc87a-dcc4-11e6-87a2-0e286be367ee.JPG)

Maybe you could advise, what may cause the issue?

Using chrlauncher 1.9.4 x64 works fine.

**Comment by henrypp** [comment]
done, thank you for report!
