### ISSUE TITLE
Duplicated taskbar icons creation.

### ISSUE THREAD

**Issue by SimpleCold** [henrypp/chrlauncher#49]
Clicking on launcher shortcut, and then pinning the window to taskbar produces a duplicate icon on next shortcut launch, or vice versa, depending on the order of clicking.
It seems to be connected to that chrlauncher.exe and chrome.exe are different programs, so the resulting icons are duplicating, would be glad to hear your opinion.

**Comment by nhantrn** [comment]
I use this work around.

a. Go to the `/bin/` folder where the `chrome.exe` is located and pin it to the taskbar.
b. Now right-click pinned icon > right-click again on chrome item and click on Properties
c. Enter this command switch `--user-data-dir="..\profile" --ppapi-flash-path="..\plugins\pepflashplayer.dll" --ppapi-flash-version=25.0.0.127` after target location.

Note that this will launch chrome.exe and not the chrlauncher so you won't get its update functions etc.

**Comment by henrypp** [comment]
There was no solution to union chrlauncher and chromium tasbar icon.

**Comment by bingoxo** [comment]
> There was no solution to union chrlauncher and chromium tasbar icon.

is there any solution now ?
