### ISSUE TITLE
Flashplayer load error

### ISSUE THREAD

**Issue by GHosTiKuS** [henrypp/chrlauncher#51]
Hello, there is error with flash player loading thru chrlauncher.
Tryed all versions of chromium (dev-official, dev-codecs-sync, stable-codecs-sync) and removed "--disable-component-update" from cmd line. No use.
Then i commented "FlashPlayerPath=", add to "ChromiumCommandLine=" "--ppapi-flash-path="(full_path)\plugins\pepflashplayer.dll" --ppapi-flash-version=24.0.0.194" and now all works.
But it's not comfortable to update flash now.

(I'm on windows 7 without admin rights)

**Comment by henrypp** [comment]
@GHosTiKuS what version do you have?

**Comment by GHosTiKuS** [comment]
chrlauncher 2.0.0.0 (SHA1 - 7713d497425d6dc3d4e76909617db8d452b1c268)

Chromium: 55.0.2883.87 (Official Build) (64-bit)
Revision: 12203fa1bfc7f10c98bcbceaa11161fd1d1c17f8
OS: Windows 
JavaScript: V8 5.5.372.32
Flash: 24.0.0.194
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
Command Line: "x:\GHosT\Browsers\ChromiumPortable\bin\chrome.exe" --user-data-dir="..\profile" --no-default-browser-check --allow-outdated-plugins --ppapi-flash-path="x:\GHosT\Browsers\ChromiumPortable\plugins\pepflashplayer.dll" --ppapi-flash-version=24.0.0.194 --flag-switches-begin --enable-features=RunAllFlashInAllowMode --flag-switches-end

also checked on:
Chromium: 58.0.2988.0 (Official Build) (64-bit)
Revision: 2bcbc12230b01813e2cc5efb02f10a8da79f88ce-refs/heads/master@{#445274}
OS: Windows 
JavaScript: V8 5.7.492
Flash: (Disabled)
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.2988.0 Safari/537.36
Command Line: "d:\Temp\ChromiumPortable_\bin\chrome.exe" --user-data-dir="..\profile" --no-default-browser-check --allow-outdated-plugins --flag-switches-begin --flag-switches-end

**Comment by henrypp** [comment]
need upgrade, latest chrlauncher is 2.2 and ppapi bug is gone!
