### ISSUE TITLE
Opening a link from an application is bugged.

### ISSUE THREAD

**Issue by Ashymad** [henrypp/chrlauncher#52]
Opening a link to some site from, for example, Thunderbird or Skype opens not only the link but 4 additional tabs as well. In the order from left to right, tabs opened are:  "url/", "--", your link, "http://--ppapi-flash-path%3Dc/Program%20Files/ChrLauncher/plugins/pepflashplayer.dll", "http://--ppapi-flash-version%3D24.0.0.194/".
I am using version 2.2

**Comment by henrypp** [comment]
What command line arguments is set to Chromium? I mean with which arguments started Chromium (not ini config), you can see it in Process Hacker (or Process Monitor). Please tell me!

**Comment by Ashymad** [comment]
The full command line (from procexp) is: "C:\Program Files\ChrLauncher\bin\chrome.exe" --user-data-dir=..\profile --no-default-browser-check --allow-outdated-plugins --disable-component-update --ppapi-flash-path="C:\Program Files\ChrLauncher\plugins\pepflashplayer.dll" --ppapi-flash-version="24.0.0.194"

**Comment by henrypp** [comment]
There is no problem with command line. Can you give me arguments when bug, which you are described, will happen?

**Comment by Ashymad** [comment]
There is a problem, with these arguments. Instead of: `-- "/url" -- "http://www.google.pl/"`, there should be just `"http://www.google.pl"`. If I paste the command line from my previous comment the bug happens, but if I remove the `-- "/url" --` only the Google tab is opened as it should.

**Comment by henrypp** [comment]
i think it problem because you are used old SetDefaultBrowser script. run latest script version from binary directory.

**Comment by Ashymad** [comment]
I've run the new script and now only 2 additional tabs open. The command line now, instead of  `-- "/url" -- "http://www.google.pl/"` has `-- "http://www.google.pl/"`, however there is still the unwanted `--`. Which causes the problem.

**Comment by henrypp** [comment]
2.3 fixed
