### ISSUE TITLE
No longer open new window when ChrLauncher executed again

### ISSUE THREAD

**Issue by ilkertezcan** [henrypp/chrlauncher#53]
Firstly, thank you for _Chromium binary file name_ feature.

I use the **Cent Browser** with **ChrLauncher**.

After ChrLauncher 1.9.4, I installed new launcher (CL v2.2).

I clicked my ChrLauncher shortcut for new window (while the browser already opened).
ChrLauncher don't exectute browser once more.
Solution: Press to **CTRL N** within the browser for open new window.

**Comment by henrypp** [comment]
Solution here: https://github.com/henrypp/chrlauncher/issues/67#issuecomment-311412268

**Comment by garbb** [comment]
If you run chrlauncher.exe with a command line with anything after it, it will open a new window.
EG: `"chrlauncher.exe \"`.
