### ISSUE TITLE
I lost all my extensions going from version 58 to version 56 and from version 56 to 58

### ISSUE THREAD

**Issue by Janaue** [henrypp/chrlauncher#55]
I was unsing the version 58 updated from chrlauncher but I wanted to use the version 
Archive
No sync • No WebRTC • No Widevine • 56.0.2924.76 (433059) • Thursday, 26 Jan 2017 

from here
https://chromium.woolyss.com/#windows-64-bit

and I updated chrlauncher to 2.2 form 1.9.4. I unzipped the archive of the version 56 in 
\chrlauncher\64\bin
and disabled auto updates

and then chromium said that my profile was from a newer version so the profile cannot be loaded, but I still had my bookmarks. There is no extensions !!.

I upgraded to version 58 by enabling the updates again and the extensions are still missing.
How do I get back my extensions with their settings?

**Comment by henrypp** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=455749#c169

> Currently, if the WebData database gets corrupted, it will remain like so
> and users will keep getting the profile error dialog every time they
> sign in. The only way for the user to fix this is to recreate the profile
> or delete the corrupt file.
> This CL does for the WebData DB as is done for the History DB; when a catastrophic
> error is seen, the DB is razed.
