### ISSUE TITLE
switches interpreted as destination(s)

### ISSUE THREAD

**Issue by teknowledgist** [henrypp/chrlauncher#56]
When chrlauncher is called with a switch, it attempts to connect to the switch as if it were a URL.  Thus:
`chrlauncher /a /b`
results in a window with three tabs:
1. "a/": this site cannot be reached
2. "--":  this site cannot be reached
3. "b/": this site cannot be reached

I assume the "--" url is for the space.  If the switch(es) are "/a/b", then only one tab with the "a/b" url is not reachable.

Thanks for the useful program otherwise!

**Comment by henrypp** [comment]
2.3 fixed
