### ISSUE TITLE
launch multiple instance of chrlauncher

### ISSUE THREAD

**Issue by endmarsfr** [henrypp/chrlauncher#59]
Hi,
first of all, I want to thanks you a lot for your great job. That issue is maybe a new request.
I use several different profil for launching chromium, 
before, I was able to launch several instance of  an old chrlauncher  (using a wrapper that changes the ini file and launch chrlauncher)
I have updated crlauncher recently and now I am not able to launche several instances of crlauncher with the new version

could you please allows us to launch again several versions of crlauncher ? 

best regards

**Comment by p0s1tr0n** [comment]
Hi,
could you add option to use multiple .ini via command line.
Something like 
/ini=chrlauncher2  or /ini="C:\chromium\launcher2"

thx

**Comment by henrypp** [comment]
@p0s1tr0n, okay, asap!

**Comment by henrypp** [comment]
@sXNA it was done in 2.5
@endmarsfr it wil be in next 2.5.1 release

**Comment by endmarsfr** [comment]
Thanks a lot
now i could start several chromium using each a specific ini file.
But, unfortunetally it is impossible to launch two chrlauncher at the same time. How could i do that ?

regards
