### ISSUE TITLE
option for set proxy for chrlauncher

### ISSUE THREAD

**Issue by netroby** [henrypp/chrlauncher#61]
We have blocked from access github download. chrlauncher show network error. is it possible add .ini option let us specified proxy for chrlauncher check/download newer update chromium?

**Comment by henrypp** [comment]
Yes, it's possible. Soon.

**Comment by henrypp** [comment]
chrlauncher uses proxy configuration from IE. do you checked it?

**Comment by netroby** [comment]
Thanks for your great works

**Comment by killerpapy** [comment]
Hello,

It's possible to use authenticated PROXY ?

Thanks.

**Comment by henrypp** [comment]
@killerpapy yes

```ini
# Set proxy configuration (string):
Proxy=username:password@127.0.0.1:80
```

**Comment by killerpapy** [comment]
Hello,

Thanks but this is not working. The proxy block the URL.
Is it possible to use a Socks proxy ?

Thank you verry much.

**Comment by charleslales** [comment]
Hi,

Works fine under Win7 but fails under Win10, would you have any clue / fix?
Using Proxy=username:password@proxy:port in chrlauncher.ini

chrlauncher_debug.log
[...]
"‎29/‎04/‎2019 ‏‎17:40:35","_app_checkupdate()","0x00000000","https://chromium.woolyss.com/api/v3/?os=windows&bit=64&type=stable-codecs-sync&out=string","2.5.6"

Kind regards,

**Comment by charleslales** [comment]
Hi,
Any feedback / idea / fix maybe..?
Nothing explicit in chrlauncher_debug.log, only this added:
"‎19/‎07/‎2019 ‏‎13:21:47","_app_checkupdate()","0x00000000","https://chromium.woolyss.com/api/v3/?os=windows&bit=64&type=stable-codecs-sync&out=string","2.5.6"
Kind regards,

**Comment by injiniero** [comment]
Same problem here. Windows 10 Pro 21H2
Proxy setting not working.
Error logged:
"Error","‎09/‎05/‎2022 ‏‎7:31:34","_app_checkupdate","0x00002EFD","https://chromium.woolyss.com/api/v3/?os=windows&bit=64&type=dev-official&out=string","2.6","10.0 build 19044"

Thanks
