### ISSUE TITLE
Flash

### ISSUE THREAD

**Issue by shiioo** [henrypp/chrlauncher#64]
I see there's a closed issue for Flash, but there's no real answer to be found.

Is there actually a working setup for a portable chrome with your launcher?
I can see Chrome still finds the installed version of Flash through chrome://flash but there's nothing to be seen at chrome://components and it's not being used.
Tried the plugins from the russian page without any luck.

Should I forget about the launcher for now?

**Comment by henrypp** [comment]
> I see there's a closed issue for Flash, but there's no real answer to be found.

#57

> I managed to make it work with the sync build from http://chromium.woolyss.com/ (57 official, 32 bits). Seems that all nosync versions fail to load the plugin.

**Comment by shiioo** [comment]
Yeah, but it's not working for me.
Tried x86 & x64 sync builds, stable & dev ones too.
Nothing worked.

**Comment by henrypp** [comment]
What Chromium build, Chromium arguments and PPAPI version do you use?

I'm worked.
![erert](https://cloud.githubusercontent.com/assets/3902025/25465555/b9c737e6-2b24-11e7-9292-102e5a0a708a.png)

Chromium 60.0.3079.0 32-bit (Sync) + PPAPI 25.0.0.148 (32-bit), Win7

**Comment by shiioo** [comment]
Ah, nevermind. It's working...
I was used to Flash asking for permission before running but I was testing it on a site that doesn't allow Flash to ask. Allowing it to run prior to access it fixes my issue.
Sorry :)
