### ISSUE TITLE
Chromium opened after start of downloading an update

### ISSUE THREAD

**Issue by hohmd** [henrypp/chrlauncher#65]
I've just had a problem with update installing.
Once i open chrlauncher, it started to download update but also OPENED A CHROME. This is really not expected. It should be open CHROME while downloading update.

I've closed chrlauncher multiple times and it acts the same (so this is not "random" issue). I've tried to run RegistryCleaner.reg - it does not change anything. I've re-downloaded latest release of chrlauncher and replaced files - it does not change anything.
I've tried to change options ChromiumBringToFront and ChromiumAutoDownload - they does not help with this issue.
I've closed already running Chrome before i run chrlauncher (no chrome.exe exist).

This issue happens in chrlauncher 2.0 - current.
But this is does NOT happen with v.1.9.4.

This issue just happened today, i was using same version of chrlauncher before fine (such problem was not here). No idea what happened (just rebooted windows recently).

I am using Windows 10. I am using default chrlauncher options except for ChromiumType=stable-codecs-nosync . I am using chrlauncher v.2.3.

I was able to install update by closing chrome and only then click on 'Install Update' once update downloaded and 'Install Update' button appear. But this is very bad, not user-friendly.

**Comment by henrypp** [comment]
Hi,

chrlauncher starting Chromium and downloading updates in background - this is normal, because chrlauncher is a `LAUNCHER` and then `'updater'`.

Don't worry, on next chrlauncher start it will install downloaded update and then run Chromium.

**Comment by henrypp** [comment]
#68

**Comment by hohmd** [comment]
> Don't worry, on next chrlauncher start it will install downloaded update and then run Chromium.

Chrlauncher window persists which is not user-friendly.

Can you please make ini option to prevent Chromium launch when update is available before update? So it work like: Update, and after install update, Run, not "Run And Update".
