### ISSUE TITLE
No issue reporting if 'Install Update' not work

### ISSUE THREAD

**Issue by hohmd** [henrypp/chrlauncher#66]
If something goes wrong and update can't be automatically installed, it does not report an issue. 'Install Update' button exist but if click, nothing happens.

It should show / indicate that here's something wrong, suggest something to do (close browser), but must not be muted.

I am using Windows 10. I am using default chrlauncher options except for ChromiumType=stable-codecs-nosync. I am using chrlauncher v.2.3

**Comment by henrypp** [comment]
try 2.4
