### ISSUE TITLE
'Install Update' button usage makes chrlauncher tray icon not work - process stay forever in processlist

### ISSUE THREAD

**Issue by hohmd** [henrypp/chrlauncher#67]
Button 'Install Update' makes chrlauncher to stay in processlist forever. Icon from tray (right bottom) disappear but process stay. It is not possible to close chrlauncher without killing it's process. If i run chrlauncher again, window immideatly popup (because process not killed). But when i click to close it or minimize, icon does not go to tray.

I am using Windows 10. I am using default chrlauncher options except for ChromiumType=stable-codecs-nosync. I am using chrlauncher v.2.3

**Comment by henrypp** [comment]
chrlauncher 32-bit? windows 64-bit? it will cause bug sometimes, because chrlauncher checking existing processes for know chromium was started or not. in wow64 variant (launcher - 32, windows/chromium - 64) it will not work entirely.

howewer, try 2.4
