### ISSUE TITLE
Use HTTPS instead of HTTP

### ISSUE THREAD

**Issue by SSLAllTheThings** [henrypp/chrlauncher#69]
Change [http://chromium.woolyss.com to https://chromium.woolyss.com](https://github.com/henrypp/chrlauncher/blob/master/src/main.cpp#L15). The site does redirect to HTTPS but this would be more efficient.

The [INTERNET_FLAG_SECURE](https://msdn.microsoft.com/en-us/library/windows/desktop/aa385098(v=vs.85).aspx) flag maybe required, not sure I don't do C++

**Comment by henrypp** [comment]
OK.

**Comment by sergeevabc** [comment]
@SSLAllTheThings, is your request fulfilled? Have you verified it? Then please do close the issue as fixed.
