### ISSUE TITLE
Portability is broken

### ISSUE THREAD

**Issue by sergeevabc** [henrypp/chrlauncher#71]
```C:\Users\…\AppData\Local\Chromium``` is created unexpectedly upon launch with some Crashpad reports.
And this trace remains even after Chromium is closed, which is not acceptable if we aim for [portability][1].

What are you going to do about it, Henry?

Edit: For example, [X-Chromium launcher][2] is smart enough to remove that folder upon exit.

[1]: http://www.rlvision.com/blog/what-is-a-portable-application-and-why-should-you-use-them/
[2]: http://www.winpenpack.com/en/download.php?view.1082

**Comment by henrypp** [comment]
Portability is not broken, because _all profile settings_ stored in chromium directory.

`C:\Users\…\AppData\Local\Chromium\User Data\Crashpad` is still empty directory created by chromium at every start and wait for end of process by chrlauncher to delete this empty directory is... stupid.

to disable logging, set this arguments ` --disable-logging --disable-breakpad --disable-breakpad` empty folder still create.

**Comment by sergeevabc** [comment]
Henry, it seems you’re trying to reinvent what portability is, just to postpone the need to intervene.
Since you were lazy to visit the given definition link, let me quote the [eponymous Wikipedia article][2]:

> A portable application does not leave its files or settings on the host computer or modify the existing system and its configuration. The application does not write to the Windows registry or store its configuration files in the user's profile; instead, it stores its configuration files in the portable directory. 

Current implementation of CHRLauncher leaves traces on the host system outside its directory.
So either think of how to resolve this hastily closed issue, or at least warn too trusting users.

[1]: http://www.rlvision.com/blog/what-is-a-portable-application-and-why-should-you-use-them/
[2]: https://en.wikipedia.org/wiki/Portable_application

**Comment by henrypp** [comment]
I'm trying to tell you, how much you are right, and Wikipedia right too, but open your eyes:

> A portable application does not leave its files or settings on the host computer or modify the existing system and its configuration.
chrlauncher (it means chromium running under launcher) does not leave any file on the host computer
chrlauncher does not modify any existing system configuration (except "SetAsDefault.bat" script, but it depend on user choice).

> The application does not write to the Windows registry or store its configuration files in the user's profile;
same here. Chromium (not launcher) create empty (EMPTY!) folder (`
C:\Users\…\AppData\Local\Chromium\User Data\Crashpad`) at every start and not contain any configuration or something else.

**Comment by sergeevabc** [comment]
Launcher does not leave traces, it goes without saying, but Chromium, the very application which is wrapped by this launcher, does. Whilst various portable launchers like [PAF][1], [yaP][2], [Winpen][3] taught us to expect it would not happen.

[1]: http://www.portablefreeware.com/
[2]: http://rolandtoth.hu/yaP/
[3]: http://www.winpenpack.com/en/index.php

**Comment by henrypp** [comment]
> Chromium (not launcher) create empty (EMPTY!) folder (`
C:\Users\…\AppData\Local\Chromium\User Data\Crashpad`) at every start and not contain any configuration or something else.
