### ISSUE TITLE
InternetOpenURL() failed

### ISSUE THREAD

**Issue by Suncatcher** [henrypp/chrlauncher#72]
I get this error from time to time:

![image](https://user-images.githubusercontent.com/6388034/27141892-1b190d0c-5132-11e7-8817-cae6c5f68998.png)

**Comment by Suncatcher** [comment]
12002 code is also throwed

![image](https://user-images.githubusercontent.com/6388034/27143232-60ccdee2-5136-11e7-9816-cf65a0bd5e3f.png)

**Comment by henrypp** [comment]
try 2.4
