### ISSUE TITLE
[Request]:Please provide some method to print headers and footers

### ISSUE THREAD

**Issue by errkranjan** [henrypp/chrlauncher#73]

**Comment by henrypp** [comment]
Why?

**Comment by errkranjan** [comment]
Reports usually contains header and footers. When we make some data entry applications then we have to first generate pdf report for printing. We can generate report in HTML & CSS, but the only limit is that we cannot define headers & footers.
As you can see in the image that headers and footers will be repeated on every printed page, but there is no option to do that with HTML & CSS
![untitled](https://user-images.githubusercontent.com/20110838/27768093-b4024a70-5f28-11e7-8f29-debb6dad20a6.png)

**Comment by henrypp** [comment]
Are you sure?

**Comment by errkranjan** [comment]
ya! it will be good. if possible

**Comment by henrypp** [comment]
Some questions questions. Who are "we", what reports and how chrlauncher concerns to excel?
