### ISSUE TITLE
chrlauncher 2.4 Always Downloads 32-Bit Version of Chromium

### ISSUE THREAD

**Issue by puff-m-d** [henrypp/chrlauncher#74]
Hello,

chrlauncher 2.4 always downloads 32-bit version of Chromium...
This happens even after changing the line in chrlauncher.ini
From: ChromiumArchitecture=0
To: ChromiumArchitecture=64

**Comment by puff-m-d** [comment]
Hello,

I thought that I might need to add this issue occurs for the dev-codecs-nosync 64-bit version (the one that I use) and I have not any of the other Chromium version options to see if this same issue occurs with them.

Also, I will attach a copy of my chrlauncher.ini file in case that may be needed (had to change file extension to .txt so the file could be uploaded)...
[chrlauncher.txt](https://github.com/henrypp/chrlauncher/files/1106336/chrlauncher.txt)

**Comment by henrypp** [comment]
2.4.1 fixed

**Comment by puff-m-d** [comment]
Hello,

That was very fast! Thank you as I really appreciate all you do!
