### ISSUE TITLE
Chromium with Tor

### ISSUE THREAD

**Issue by skarsgal** [henrypp/chrlauncher#76]
Hi,
if I wish hide my IP address, I add inside chrlauncher.ini a command line with one of these string:
1. Hide my IP: 
ChromiumCommandLine=--proxy-server="socks5://localhost:9050" --host-resolver-rules="MAP * 0.0.0.0 , EXCLUDE localhost
2. Hide my IP + Incognito mode: 
ChromiumCommandLine=--incognito --proxy-server="socks5://localhost:9050" --host-resolver-rules="MAP * 0.0.0.0 , EXCLUDE localhost"

Please note that port 9050 is required by Tor.

It is possible to add to Your chrlauncher a new option like this ?:
. # Check for type of connection
. # 1             -> Normal connection (default)
. # 2             -> Hide your IP
. # 3             -> Hide your IP + Incognito mode

This avoids remembering a complicated string.
Thanks

**Comment by henrypp** [comment]
No. You may pass arguments to chromium through launcher like that:
`chrlauncher.exe --incognito --proxy-server="socks5://localhost:9050" --host-resolver-rules="MAP * 0.0.0.0 , EXCLUDE localhost"` it's all is simple.
