### ISSUE TITLE
"Download Update" button doesn't do anything.

### ISSUE THREAD

**Issue by snakyjake1** [henrypp/chrlauncher#79]
"Download Update" button doesn't do anything when clicked.

![download update](https://user-images.githubusercontent.com/8312560/28122288-a181371a-66d2-11e7-94b2-c92d34e7a8b6.png)

**Comment by woolyss** [comment]
This is because New version = null.
chrlauncher will authorize you to download a new Chromium version if it find a new Chromium version ;)
This is probably a temporary issue with the server.

**Comment by snakyjake1** [comment]
If there is no new version, why do I get the "Download update" screen?  Is there an .INI setting to only show the screen if there's a new version?

Also, these values don't change:
ChromiumLastBuild=0
ChromiumLastCheck=0
ChromiumLastVersion=0

**Comment by woolyss** [comment]
@henrypp : I have a suggestion for you. If New version = null --> Download update should be disabled. And you could put a text like "Retry later".
I tell you, I think it is a momentary server issue.
