### ISSUE TITLE
Windows 7 Search Box doesn't work with chrlauncher set as default browser

### ISSUE THREAD

**Issue by Aironfaar** [henrypp/chrlauncher#8]
On Windows 7, entering any text into the start menu's search box and selecting "Browse Internet" (sorry if this isn't the exact wording, my OS doesn't run in English) with chrlauncher set as default browser always opens a new Chromium window without performing the search.

It may be relevant that running SetDefaultBrowser.bat didn't set chrlauncher as the default browser although every output line stated success; I had to do so manually via the control panel.

**Comment by henrypp** [comment]
you set default browser via control panel?
https://github.com/henrypp/chrlauncher/issues/2#issuecomment-203390037

**Comment by Aironfaar** [comment]
Yes. After running SetDefaultBrowser.bat a couple of times, I verified that the registry keys were correctly created before and after I set chrlauncher as my default browser via control panel. The paths and command descriptions in the registry are all correct, the /url command works properly when executed from the command line as well. Only the search box doesn't want to perform properly.

By the way, I forgot to mention that I'm using the stable 64bit channel with codecs and sync.

**Comment by henrypp** [comment]
See here: http://www116.zippyshare.com/v/cxFqZBqN/file.html (64bit)
It's couple of fixes in SetDefaultBrowser.bat and many for parsing url arguments in binary. Check it!

**Comment by Aironfaar** [comment]
The fixes solved the problem. Thank you! :+1:

**Comment by henrypp** [comment]
https://github.com/henrypp/chrlauncher/releases/tag/v.1.9
