### ISSUE TITLE
Chromium wouldn't launch in non-sandbox mode

### ISSUE THREAD

**Issue by uwks911** [henrypp/chrlauncher#81]
If I run Chrlauncher from 64-bit subfolder it launches Chromium but it is then unusable: no urls can be opened, settings tab doesn't work, flags page doesn't open etc.
If I add -no-sandbox flag into chrlauncher.ini then it works fine.

**Comment by woolyss** [comment]
I run chrlauncher on 64-bit win7 and 64-bit win10 and cannot reproduce your issue.

- Which OS do you use?
- Do you use a subfolder with special characters (UTF-8 or invisible characters, for example) in its name? (Prefer ascii characters)

**Comment by uwks911** [comment]
I Use Win7 64-bit Enterprise.
Path to ChrLauncher folder is: 
c:\Users\b01271a\Documents\Programs\ChrLauncher\
So, no special characters

**Comment by henrypp** [comment]
https://github.com/henrypp/chrlauncher/issues/82#issuecomment-318606663
