### ISSUE TITLE
Crash under sandbox (Sandboxie, CIS, etc)

### ISSUE THREAD

**Issue by arashdalir** [henrypp/chrlauncher#82]
I'm getting an error when launching the chrlauncer, as shown in following image, with provided details. Have I forgot to install a dependency or something?

![image](https://user-images.githubusercontent.com/2896170/28411941-caebb424-6d42-11e7-89ff-1862f2bdae02.png)

```
Problem signature:
  Problem Event Name:	BEX
  Application Name:	chrlauncher.exe
  Application Version:	2.3.0.0
  Application Timestamp:	58a2857d
  Fault Module Name:	cmdvrt32.dll
  Fault Module Version:	10.0.1.6258
  Fault Module Timestamp:	5964b274
  Exception Offset:	0001b625
  Exception Code:	c0000417
  Exception Data:	00000000
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	af33
  Additional Information 2:	af3317c6a2758a1749d944994b2987c1
  Additional Information 3:	7a61
  Additional Information 4:	7a6183539450635e30fa3df05fcd2904
```

**Comment by henrypp** [comment]
on latest (!) 2.4.1 the same?

**Comment by arashdalir** [comment]
unfortunately yes!

```
Problem signature:
  Problem Event Name:	BEX
  Application Name:	chrlauncher.exe
  Application Version:	2.4.1.0
  Application Timestamp:	5952b021
  Fault Module Name:	cmdvrt32.dll
  Fault Module Version:	10.0.1.6258
  Fault Module Timestamp:	5964b274
  Exception Offset:	0001b625
  Exception Code:	c0000417
  Exception Data:	00000000
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	af33
  Additional Information 2:	af3317c6a2758a1749d944994b2987c1
  Additional Information 3:	3d17
  Additional Information 4:	3d1793eb82ff7b016b53c27611786bea
```

**Comment by henrypp** [comment]
no dependencies. what happening? what do you change?

**Comment by arashdalir** [comment]
well! did nothing! downloaded the tools and chromium and tried to execute it!

**Comment by woolyss** [comment]
The problem is not relative to chrlauncher. Please can you follow this tutorial to fix error BEX: https://www.youtube.com/watch?v=cEkoK3EHOlU

**Comment by uBlock-user** [comment]
I'm facing a different issue/ Whenever I try to extract chrlauncher from the .zip from the latest release I get this error

![](https://i.gyazo.com/2a1f0a0015839be9b873cd86d74b3c8f.png)

**Comment by henrypp** [comment]
@uBlock-user use normal file archiver, like [7-Zip](http://www.7-zip.org/), not internal Windows BS~.

**Comment by uBlock-user** [comment]
@henrypp But it doesn't happen with v2.4.0 and prior releases, so something is broken with the packaging, you must try to fix that rather than giving me alternatives.

**Comment by arashdalir** [comment]
@woolyss  
windows is throwing the following error when I try to add the app to DEP:
![image](https://user-images.githubusercontent.com/2896170/28561463-d7781b80-711e-11e7-84a1-e2471bf30daf.png)

**Comment by henrypp** [comment]
@uBlock-user nothing is broken, packed with LZMA2 - explorer does not support this!

**Comment by uBlock-user** [comment]
@henrypp and what did you pack v2.4.0 with ? because that works and all other releases too

**Comment by henrypp** [comment]
@uBlock-user old versions packed with Deflate with low compression ratio.

**Comment by uBlock-user** [comment]
so you're no longer using Deflate anymore ?

**Comment by henrypp** [comment]
No. As you're see! Have problem with using normal unpacker?

**Comment by uBlock-user** [comment]
Is that a question to me or you're saying as a statement ?

**Comment by henrypp** [comment]
> Have problem with using normal unpacker?

Yes, this is question, to you.

**Comment by uBlock-user** [comment]
Yes, I do. Windows built in zip extracter should work but you changed the algorithm and now it doesn't work, so for this algorithm I will have to use 7-zip which is unnecessary and pointless as the file size is so low like in KBs, what are you trying to compress here huh ? Why not just just use deflate that Windows supports and continue packing with that ? 

You know what they say, **If it ain't broke, don't fix it.**

**Comment by henrypp** [comment]
@uBlock-user,

> Yes, I do. Windows built in zip extracter should work but you changed the algorithm and now it doesn't work, so for this algorithm I will have to use 7-zip which is unnecessary and pointless as the file size is so low like in KBs, what are you trying to compress here huh ? Why not just just use deflate that Windows supports and continue packing with that ? 

No. I don't think so, mate.

Micosoft using his own algorithms and **ignore all open ISO standarts**, [like all other Micosoft BS~ tooolz](https://en.wikipedia.org/wiki/Embrace,_extend_and_extinguish) (watch wiki).

>7-zip which is unnecessary and pointless

How about that: not all portable applications packing binaries into .zip format, .7z, .rar still alive. 7-zip still pointless? 7-zip is open-source, respects the open ISO standarts and supports most archive types.

I'm recommend you to use only open-source and not proprietary because it's closed and no one know what inside.

> You know what they say, **If it ain't broke, don't fix it.** 

Nothing is broken, anyway!

**Comment by arashdalir** [comment]
@uBlock-user by the way, speaking of sayings, have you heard about "don't hijack other people's thread which isn't related to your issue for your own use"? it's the 101 of software issue tracking: each issue should be defined in its own thread for so many different reasons. My initial problem with the error code is now shadowed by a discussion which is completely irrelevant and I don't seem to be able to get any advice on my issue because you don't like to install 7-zip.
Although I'd say both of you are to some extent right about the issue with tool compatibility and so on, I cannot understand why this issue is not being discussed in a separate thread. 
@henrypp: about the zip issue, yes, you are right, open-source apps are great and that's the reason we are all here. I find the idea great and support open source developers as far as I can, hence the error reporting here. but just fyi: the point of portable apps is that you don't need any extra tools installed on a system. in some cases, we cannot install any third party apps like 7-zip or so on the host system and still need a portable chromium. Although @woolyss 's chromium is also runnable without your tool and a clever person can also achieve "most" of what you have done with a batch file. if I needed to install an extra app to use a portable app, I wouldn't call your app portable anymore...

**Comment by uBlock-user** [comment]
@henrypp 

> Micosoft using his own algorithms and ignore all open ISO standarts, like all other Micosoft BS~ tooolz (watch wiki).

Oh yeah so why did you used that till now ? All this time you were using MS's algorithm even though you knew about this and now all of a sudden you decided to change algorithm because you don't like the way MS works!!!! That's bullshit!!


> No. I don't think so, mate.

I'm not asking for your opinion, so it doesn't matter what you think, what you did is NOW affecting all the users and that's the issue here at hand.

> How about that: not all portable applications packing binaries into .zip format, .7z, .rar still alive. 7-zip still pointless? 7-zip is open-source, respects the open ISO standarts and supports most archive types

I don't care! Everything was working fine till v2.4.0 but you had to ruin it by changing algorithm because you don't like the way MS works and because of that now I have to use a third party software just to extract chrlauncher from the zip,and  that's a load of fucking bullshit and that's on you man!

> I'm recommend you to use only open-source and not proprietary because it's closed and no one know what inside.

and I recommend you stop messing with the code because it worked just fine before you decided to change algorithm because you don't like the MS works. If you're not going to do as I say, then don't be a smart ass and recommend something that I won't do. I know what proprietary software is! I'm using Chromium instead of Chrome for crying out loud! All my extensions are open source, so please keep don't bother condescending me !

> Nothing is broken, anyway!

Except you decided to be a smart ass and break the entire thing by changing the god damn algorithm and now I'm facing this https://github.com/henrypp/chrlauncher/issues/82#issuecomment-317313885

So yeah IT. IS. BROKEN. No thanks to you.

**Comment by arashdalir** [comment]
@uBlock-user no one is forcing you to use the tool. please respect the developer or get lost. you are not paying for this tool and it's an "as-is" license. take it or leave it. you are disrespectful and condescending to everyone here.

**Comment by uBlock-user** [comment]
> by the way, speaking of sayings, have you heard about "don't hijack other people's thread which isn't related to your issue for your own use"? it's the 101 of software issue tracking: each issue should be defined in its own thread for so many different reasons. My initial problem with the error code is now shadowed by a discussion which is completely irrelevant and I don't seem to be able to get any advice on my issue because you don't like to install 7-zip.

No need to get butthurt, it was a matter of asking why he did that so I had to ask and I didn't bother to create a new one because I thought the issue lied with the chrlauncher as you can see in my first post, so yeah it's perfectly fine posting here as intially it appeared that it was related to chrlauncher itself. You carry on, I have got nothing further to say. He's made up his mind and won't be changing the algo back.

**Comment by arashdalir** [comment]
@uBlock-user  do you understand anything about software development mate? you are the only person who is condescending and impolite here.

**Comment by uBlock-user** [comment]
@arashdalir No mate you get lost, I'm talking with him, not with you. You're the one  who's acting like butthurt idiot who's now nagging me simply because he's not going anywhere in regards to his issue.

**Comment by uBlock-user** [comment]
@arashdalir I don't need a lesson from a moron with one repository in his profile and acting all high and mighty. Stay butthurt all you want, it won't resolve the issue that you're on Windows 7.

**Comment by arashdalir** [comment]
yes, because I publish things with our company's account and not that of my own you bigot!
you clearly don't understand how some enterprises work! I have no choice but to use windows 7 because the client has windows 7 on their machines...

**Comment by henrypp** [comment]
@uBlock-user tl;dr;
@arashdalir any defence software installed? maybe issue #83 have any connection. chrlauncher tested on clean winxp/win7/win10 and my win7 w/o any crashes or something like that at startup.

**Comment by arashdalir** [comment]
>any defence software installed? maybe issue #83 have any connection. chrlauncher tested on clean winxp/win7/win10 and my win7 w/o any crashes or something like that at startup
I'll test it right away.

> Is not everyone installed 3rd-party archiver?
well, practically no. as said, there are some enterprises which define their own infrastructure and don't allow any other app to be installed. so, 7-zip or other decompressors aren't always automatically installed. as said earlier, I understand your point, it's a must-have, and we install it on every system we manage, as we rely on its password protection and encryption features, but it's not a fix thing unfortunately.
I would generally suggest you add a simple terms of use/license to your project mate, it might at least be handy if a discussion escalates again. and a list of dependencies based on versions might also help ;)

**Comment by arashdalir** [comment]
>> any defence software installed? maybe issue #83 have any connection. chrlauncher tested on clean winxp/win7/win10 and my win7 w/o any crashes or something like that at startup
>I'll test it right away.

okay, you were right. the Comodo Internet Security automatically sandboxed the software without issuing a warning, which caused the app to fail on start.

**Comment by arashdalir** [comment]
I'll close the issue if it's okay for you. 
Thanks for your support.

**Comment by henrypp** [comment]
I did not test any of my app under sandboxed area, need tests. ASAP i think it possible to fix.
