### ISSUE TITLE
Downloading binaries from github gives a warning!

### ISSUE THREAD

**Issue by technout** [henrypp/chrlauncher#83]
When trying to download the binary files from github (this url:
https://github.com/henrypp/chrlauncher/releases/download/v.2.4.1/chrlauncher-2.4.1-bin.zip)

I get a firefox warning: (in dutch)
In English: http://www.support.mozilla.org/kb/how-does-phishing-and-malware-protection-work

What is wrong with this link or binary files? I almost never get a message like this and it is very scary!

(the message in dutch)
"Misleidende website!

De website op github-production-release-asset-2e65be.s3.amazonaws.com is gerapporteerd als een misleidende website en is geblokkeerd op basis van uw beveiligingsvoorkeuren.

Misleidende websites zijn ontworpen om u iets gevaarlijks te laten doen, zoals het installeren van software, of het delen van uw persoonlijke gegevens, zoals wachtwoorden, telefoonnummers of creditcardgegevens.

Het invoeren van persoonlijke gegevens op deze webpagina kan leiden tot diefstal van identiteitsgegevens of andere fraude."

**Comment by technout** [comment]
Problem seems to be solved. The warning message from Firefox is gone.

**Comment by henrypp** [comment]
Nice, but maybe it temporary)

**Comment by woolyss** [comment]
@henrypp : You can close this issue ;)
It was a bug about Google's Safe Browsing. It is fixed.
https://www.ghacks.net/2017/07/25/firefox-blocks-all-github-release-downloads-as-deceptive/
