### ISSUE TITLE
host the chrome zip on my network

### ISSUE THREAD

**Issue by gubas** [henrypp/chrlauncher#86]
I want to host the chrome zip on my network.

I think i can manage it with the "ChromiumUpdateUrl" parameter.

But how can i do it ?

**Comment by henrypp** [comment]
Why do you need this? @woolyss will help you.

**Comment by henrypp** [comment]
you need hosting (localhost for start is okay) for create REST API script and some programming skills.

"chromiumupdateurl" is url to your script. (important notice: all percent-formating operand (%d, %s) ang GET arguments need to be ordered as in chrlauncher.ini example).

returned data is single string as "key:val" with semicolon delimeter.

for example you can open "chromiumupdateurl" with replaced percents as %d to 32 or 64 and %s to <any of build type> (all values in chrlauncher.ini).

i cannot post any better example for some time, but all is simple.

23 августа 2017 г. 13:16:42 GMT+06:00, Guigs <notifications@github.com> пишет:
>Because i want to keep some version on my network.
>
>And sometimes i didn't have internet on some parts on my network.
>
>@woolyss, can you help me ?

**Comment by gubas** [comment]
thank you, it works like a charm 👍

**Comment by TPS** [comment]
@gubas @henrypp Maybe y'all might want to post this in the [wiki](https://github.com/henrypp/chrlauncher/wiki) also, rather than only in this now-closed issue?  This seems like it'd be useful to a wider audience.

**Comment by saxobroko** [comment]
how do i do this with a github download link?
