### ISSUE TITLE
Launching the program from chrlauncher.exe works but buggy when launching from chromium.exe

### ISSUE THREAD

**Issue by Tom4tot** [henrypp/chrlauncher#87]
Dear Henry++,

First of all, thanks a lot for your programs. I've discovered lately this program and Simple Wall and they really enhance my Windows Experience. You're doing amazing job, keep it up!

However, I have an issue I didn't have yesterday. I've reinstalled Windows today on my laptop.

The installation went fine but now when I launch chrlauncher.exe, the programs starts correctly. However, if I launch "chrome.exe" in the bin folder or through the task bar (after pinning it), it launches an new session of Chromium... So it's quite annoying.. Any ideas what it could be ?

It's probably nothing but I can't find any solution...

Thanks.

**Comment by henrypp** [comment]
Hi,
There is only one solution, see here #49.

**Comment by Tom4tot** [comment]
Thanks, amazing. 👍

**Comment by henrypp** [comment]
@Tom4tot ot, dont worry, my imperfection, f.a.q. section is required!
