### ISSUE TITLE
Please be Advised Chrlauncher 2.4.1 has ADWARE

### ISSUE THREAD

**Issue by ChelovekH** [henrypp/chrlauncher#88]
After downloading your software from the official link:
[https://github.com/henrypp/chrlauncher/releases/tag/v.2.4.1](url)

Unpacking and running the 64 bit chrlauncher.exe `  MD5: d74999031635bb43d553c789ca41ffa4`
I receive the following warning when I try to download Chromium from AVIRA Internet Security

> Type:
File:	C:\Users\HomePc\AppData\Local\Chromium\Application\bin\chrome_elf.dll
Status:	Infected
Quarantaineobject:	709a1cbe.qua
Repaired:	No
Uploaded to Avira:	No
OS:	Windows XP/VISTA Workstation/Windows 7
Search program:	8.03.48.38
Virusdefinitiion file:	8.14.30.54
Detection:	ADWARE/SpeedBit.Gen7
Date/time:	07/10/2017, 12:24 <

I think it is safe to say that this is Not a false-positive

**Comment by Phoenix1747** [comment]
Another good example why antivirus software is crap. Please, this is a false positive.

If you don't trust me, trust Virustotal and 60 AV programs: https://www.virustotal.com/#/file/93ad7515c262154760f3b20731c516ac0e96c383c4192e6c7193d6fe5b9011dc

**Comment by woolyss** [comment]
This is a false positive ;)

chrlauncher downloads the ZIP file of Chromium, unzip and installs it itself. In this case, it is not infected by malware (https://chromium.woolyss.com/#malware) but is a false positive of Avira antivirus.

You can check "chromium-sync.zip" yourself:
- https://www.virustotal.com/#/file/b2dc4d47b19eb60dca8151995293d2005bc7e2626931dc34cfe70b800a801aec
- https://virusscan.jotti.org/en-US/filescanjob/600bt4u3nu

Source: https://chromium.woolyss.com/?all=1#comment-2467
(This link load all site comments)
