### ISSUE TITLE
chrlauncher.exe -incognito for temporary incognito mode

### ISSUE THREAD

**Issue by spacedingo** [henrypp/chrlauncher#9]
If I need to open Chromium in incognito mode, I have to edit the chrlauncher.ini : /
Thanks for the launcher

**Comment by henrypp** [comment]
today released https://github.com/henrypp/chrlauncher/releases/tag/v.1.9, now you can pass arguments through chrlauncher like this: chrlauncher --incognito "www.example.to", opened link in incognito.
