### ISSUE TITLE
[Suggest] RobRich dev build

### ISSUE THREAD

**Issue by kowith337** [henrypp/chrlauncher#90]
Is it possible to download dev (lkcr) build that compiled by RobRich?
but...
- All of RobRich builds only available for Win64
- Have NoSync, NoWebRTC, No WideVine
- Have different build between WPO and PGO.

**Comment by henrypp** [comment]
Yes, i think it possible.

@woolyss, what type of RobRich builds?

**Comment by woolyss** [comment]
Hello,
It is already available for months (because there are portable version of Rob builds on chromium.woolyss.com! ;)

Change a setting in **chrlauncher.ini** file.
* `ChromiumType=dev-clang-nosync` for CLANG build
* `ChromiumType=dev-pgo-nosync` for PGO build

**Comment by kowith337** [comment]
Thank you very much! @henrypp @woolyss
