### ISSUE TITLE
How do I force chrlauncher.exe to update chromium too?

### ISSUE THREAD

**Issue by P4risAndStuff** [henrypp/chrlauncher#92]
If chrlauncher.exe just acts as a shortcut to chromium, what do i do to make it first install an update to chromium upon running the executable? Mind this dumb question if it is one, but I'm a noob.

**Comment by woolyss** [comment]
Set `ChromiumCheckPeriod=-1` to force Chromium update in your **chrlauncher.ini** file.
 https://github.com/henrypp/chrlauncher/blob/master/bin/chrlauncher.ini

**Comment by P4risAndStuff** [comment]
Legend

**Comment by P4risAndStuff** [comment]
this didn't work, what should i do?

**Comment by woolyss** [comment]
Delete the **bin**/ folder

**Comment by P4risAndStuff** [comment]
> Delete the "**bin**" folder
> (if `ChromiumDirectory=.\bin` , in your **chrlauncher.ini** file)
> 
> Which OS version (windows 10, 8, 7) ?

Windows 10. And yeah, `ChromiumDirectory=.\bin` is there. Should I still delete the `bin` folder?

**Comment by woolyss** [comment]
@P4risAndStuff : sorry for delay. Yes you can remove it. This is only the folder for Chromium binary files. There are no addon, no user data.

**Comment by P4risAndStuff** [comment]
Deleted it and opened chrlauncher.exe - it actually did the "update" but it basically just re-installed Chromium 64.0.3259.0 instead of updating to a newer version like 64.0.3265.0. Is that version not ready to be supported with chrlauncher yet or something? It isn't really even a big deal anyways, 3259 is super close to 3265. Just wondering what's going on here.

**Comment by woolyss** [comment]
It depends of the canal (check `ChromiumType=***` in your chrlauncher.ini file).

For example:
- `dev-official` is updated each hour (today, it is 64.0.3266.0 / 515835)
- `dev-codecs-sync` is updated by nik - a developer -  (today, it is still 64.0.3259.0 / 514062)

**Comment by P4risAndStuff** [comment]
Oh, I get it now, thank you so much! Issue resolved now.
