### ISSUE TITLE
Build fails 

### ISSUE THREAD

**Issue by 912d** [henrypp/chrlauncher#93]
[Previous one ](https://github.com/henrypp/chrlauncher/issues/77) was closed and locked without any word. 

1 download zip project from github
2 unzip
3 open sln file in Microsoft Visual Studio
4 build and receive errors below

`1>------ Build started: Project: chrlauncher, Configuration: Release Win32 ------
1>rapp.cpp
1>c1xx : fatal error C1083: Cannot open source file: '..\routine\rapp.cpp': No such file or directory
1>routine.cpp
1>c1xx : fatal error C1083: Cannot open source file: '..\routine\routine.cpp': No such file or directory
1>rstring.cpp
1>c1xx : fatal error C1083: Cannot open source file: '..\routine\rstring.cpp': No such file or directory
1>main.cpp
1>src\main.h(9): fatal error C1083: Cannot open include file: 'rconfig.h': No such file or directory
1>Done building project "chrlauncher.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

**Comment by henrypp** [comment]
How about this #78?
