### ISSUE TITLE
starting chrlauncher, nothing happens

### ISSUE THREAD

**Issue by oz42** [henrypp/chrlauncher#97]
When I start chrlauncher 2.4.3, it is in the process list for a few seconds and then closes. No GUI is displayed.
System: Windows 7 x64

**Comment by rugabunda** [comment]
Same issue here!

**Comment by rugabunda** [comment]
System Windows 7 X64

**Comment by rugabunda** [comment]
Its using a previously known malicious ip for updating, apparently and is blocked if you are using skynet or some similar app. https://otx.alienvault.com/indicator/ip/213.186.33.19

unbanning this ip may allow it through but you may be placing yourself at risk.

**Comment by oz42** [comment]
No, my IP address was more like from this pool: 109.41.0.0/17

**Comment by henrypp** [comment]
fixed
